---
title: "Causal Inference: Average (Marginal) Treatment Effects"
date: "2023-MAR-28"
bibliography: /Users/joseph/GIT/templates/bib/references.bib
editor_options: 
  chunk_output_type: console
format:
  html:
    warnings: FALSE
    error: FALSE
    messages: FALSE
    code-overflow: scroll
    highlight-style: oblivion
    code-tools:
      source: true
      toggle: FALSE
html-math-method: katex
reference-location: margin
citation-location: margin
cap-location: margin
code-block-border-left: true
---


```{r}
#| echo: FALSE
#| warning: FALSE

# WARNING:  COMMENT THIS OUT. JB DOES THIS FOR WORKING WITHOUT WIFI
#source("/Users/joseph/GIT/templates/functions/libs2.R")

# WARNING:  COMMENT THIS OUT. JB DOES THIS FOR WORKING WITHOUT WIFI
#source("/Users/joseph/GIT/templates/functions/funs.R")

# ALERT: UNCOMMENT THIS AND DOWNLOAD THE FUNCTIONS FROM JB's GITHUB
# source(
#   "https://raw.githubusercontent.com/go-bayes/templates/main/functions/experimental_funs.R"
# )

# source(
#   "https://raw.githubusercontent.com/go-bayes/templates/main/functions/experimental_funs.R"
# )
# for making graphs
library("tinytex")
library("extrafont")
loadfonts(device = "all")
```


::: {.callout-note}
**Required**
- [@hernan2024WHATIF] Chapters 1-3 [link](https://www.dropbox.com/scl/fi/9hy6xw1g1o4yz94ip8cvd/hernanrobins_WhatIf_2jan24.pdf?rlkey=8eaw6lqhmes7ddepuriwk5xk9&dl=0)


**Optional**
- [@neal2020introduction] Chapter 1-2 [link](https://www.dropbox.com/scl/fi/9hy6xw1g1o4yz94ip8cvd/hernanrobins_WhatIf_2jan24.pdf?rlkey=8eaw6lqhmes7ddepuriwk5xk9&dl=0)
:::

::: {.callout-important}
## Key concepts for the test(s):
  - **The Fundamental Problem of Causal Inference**
  - **Causal Inference in Randomised Experiments**
  - **Causal Inference in Observational Studies - Average (Marginal) Treatment Effects**
  - **Three Fundamental Assumptions for Causal Inference**
:::

::: {.callout-important}
## For the lab, copy and paste code chunks following the "LAB 6" section.
:::


# Seminar

## Learning Outcomes

- You will understand why causation is never directly observed.

- You will understand how experiments address this "causal gap."

- You will understand how the application of three principles from experimental research allow human scientists to close this "causal gap" when making inferences about a population as whole -- that is, inferences about "marginal effects."


## Opening 


Robert Frost writes, 

> Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth;

>Then took the other, as just as fair,
And having perhaps the better claim,
Because it was grassy and wanted wear;
Though as for that the passing there
Had worn them really about the same,

>And both that morning equally lay
In leaves no step had trodden black.
Oh, I kept the first for another day!
Yet knowing how way leads on to way,
I doubted if I should ever come back.

>I shall be telling this with a sigh
Somewhere ages and ages hence:
Two roads diverged in a wood, and I—
I took the one less traveled by,
And that has made all the difference. 
-- The Road Not Taken


At the heart of Frost's poem is the sad poignancy:

**“And sorry I could not travel both. And be one traveller$\dots$”**  


## Introduction: Motivating Example

Consider the following cross-cultural question: 

> Does bilingualism improve cognitive abilities in children? 

There is evidence that bilingual children perform better oat cognitive tasks, but is learning more than one language a confounding factor? 

How can we know?  Each child might respond as the traveller in Frost's poem:

"And sorry I could not travel both. And be one traveller$\dots$"


## Part 1: The Fundamental Problem of Causal Inference as a Missing Data Problem 

Humans think in images, words, and songs -- sometimes dance. I believe that every inclination to write out ideas in math should be presumed guilty until proven innocent.

However, I have found that a little mathematical notation helps to clarify the concepts.

To understand the fundamental problem of causal inference, we first define two potential outcomes for each individual in our study:

Let $Y$ and $A$ denote random variables. Mathmatically, we formulate a causal question by asking whether assigment to treatment $A = a$ will lead to a difference to the outcome $Y$.  

Let $A = 1$ denote getting the "bilingual" treatment, and $A = 0$ denote getting the monolingual treatment. Assume these are the only two treatments of interest. 

- $Y_i(a = 1)$ The cognitive ability of child $i$ if they were bilingual. This is the counterfactual outcome when treatement $A = (a  =  1)$.

- $Y_i(a = 0)$:: The cognitive ability of child $i$ if they were monolingual. This is the counterfactual outcome when $A = (a = 0)$.

Using this notation, we may define a quantitative causal effect of bilingualism on cognitive ability for individual $i$ as the difference between these potential outcomes:


$$
\text{Causal Effect}_i = Y_i(1) - Y_i(0)
$$

We say there is a causal effect if: 

$$
Y_i(1) - Y_i(0)  \neq 0
$$

Writing out our contrast of interest this way makes it clear that we cannot compute this contrast directly from any data we may observe because individuals experience only **one** treatment condition:

$$
Y_i|A_i = 1 \implies Y_i(0)|A_i = 1~ \text{is counterfactual}
$$
and:


$$
Y_i|A_i = 0 \implies Y_i(1)|A_i = 1~ \text{is counterfactual}
$$


::: footer
"**And sorry I could not travel both. And be one traveller, long I stood** $\dots$"
:::



### Average Treatment Effect in randomised controlled experiments work from assumptions



$$
\text{Average Treatment Effect} = \left[ \begin{aligned}
&\left( \underbrace{\mathbb{E}[Y(1)|A = 1]}_{\text{observed}} + \textcolor{cyan}{\underbrace{\mathbb{E}[Y(1)|A = 0]}_{\text{unobserved}}} \right) \\
&- \left( \underbrace{\mathbb{E}[Y(0)|A = 0]}_{\text{observed}} + \textcolor{cyan}{\underbrace{\mathbb{E}[Y(0)|A = 1]}_{\text{unobserved}}} \right)
\end{aligned} \right]
$$


In this expression, $\mathbb{E}[Y(1)|A = 1]$ represents the average outcome when the treatment is given, which is observable. However, $\mathbb{E}[Y(1)|A = 0]$ represents the average outcome if the treatment had been given to those who were untreated, which remains unobservable. Similarly, the quantity $\mathbb{E}[Y(0)|A = 1]$ also remains unobservable.  Note that the problem isn't merely one of statistical analysis on the data. **The problem is that the relevant data to identify individual causal effects are missing.** Thus, it is evident that the fundamental problem of causal inference is an ever-present concern even in experiments!

All the data we require for invidual causal inferences are missing, nevertheless, because the treatments have been randomised, the data we observe from randomised controlled experiments can allow us to infer what would happen, **on average** if the treatment were applied to the population from which the participants were sampled. 

We may call this causal affect the "Average Treatment Effect" or equivalently, the "Marginal Effect of the Treatment." 


### How do We Obtain Average Treatment Effects From Non-Randomised Observational Data?

Under stronger assumptions, we may sometimes infer causal effects from associations in data, even if the treatment variable $A$ has not been randomised. 


$$
\text{ATE} = \sum_{l} \left( \mathbb{E}[Y|A=1, \textcolor{cyan}{L=l}] - \mathbb{E}[Y|A=0, \textcolor{cyan}{L=l}] \right) \times \textcolor{cyan}{\Pr(L=l)}
$$

Where $L$ denotes the set of measured covariates such that $A\coprod Y(a)|L$





#### Focus
- Application of regression and simulation in R for ATE estimation


  
## Overview
  
  
  
## Notes

Consider that in the causal inference literature, we may write this contrast two potential outcomes under treatment as:


$$
\text{Causal Effect}_i = Y_i^{a=1} - Y_i^{a=0} 
$$

or

$$
\text{Causal Effect}_i = Y_i^{1} - Y_i^{0} 
$$

or:


$$
\text{Causal Effect}_i = Y_{1} - Y_0 
$$
Where subscripts are dropped.  You will soon encounter that many 