---
title: "Causal Inference: Effect-Modification and Interaction"
date: "2023-APR-22"
execute:
  warning: false
format: 
 html:      
  html-math-method: katex
---

```{r}
#| include: false
# for information about this template: https://github.com/mikemahoney218/quarto-arxiv/blob/main/template.qmd
#libraries and functions
# read libraries
library("tinytex")
library(extrafont)
loadfonts(device = "win")

# read functions
#source("/Users/joseph/GIT/templates/functions/funs.R")
```

::: {.callout-note}
**Required**
- [@hernan2024WHATIF] Chapters 4-5 [link](https://www.dropbox.com/scl/fi/9hy6xw1g1o4yz94ip8cvd/hernanrobins_WhatIf_2jan24.pdf?rlkey=8eaw6lqhmes7ddepuriwk5xk9&dl=0)

**Optional**
- [@vanderweele2007FOURTYPESOFEFFECT] [link](https://www.dropbox.com/scl/fi/drytp2ui2b8o9jplh4bm9/four_types_of_effect_modification__a.6.pdf?rlkey=mb9nl599v93m6kyyo69iv5nz1&dl=0)
- [@vanderweele2009distinction] [link](https://www.dropbox.com/scl/fi/srpynr0dvjcndveplcydn/OutcomeWide_StatisticalScience.pdf?rlkey=h4fv32oyjegdfl3jq9u1fifc3&dl=0)
:::

::: {.callout-important}
## Key concepts for the test(s):
  - **Effect Modification**
  - **Interaction/Moderation**
  - **Heterogeneous Treatment Effects**
  - **Causal Mediation**

:::




## Review




## Concepts


#### Interaction as a joint intervention

This form of interaction occurs when the combined effect of two interventions (or treatments) is different from what would be expected based on their individual effects. 

Consider two treatments, denoted as $A$ and $B$, and their outcome as $Y$. A joint intervention causal interaction implies that the effect of $A$ and $B$ together on $Y$ (denoted as $Y(A,B)$) is not merely the sum of their individual effects. 

For instance, consider the effect of beliefs in Big Gods (exposure $A$)
on social complexity (outcome $Y$), potentially influenced by a
culture's monumental architecture (exposure $B$). To assess the
individual and combined effects of $A$ and $B$, we look for evidence of
causal interaction on the difference scale. Evidence for interaction
would be present if the following inequality were to hold:

$$\bigg(\underbrace{\mathbb{E}[Y(1,1)]}_{\text{joint exposure}} - \underbrace{\mathbb{E}[Y(0,0)]}_{\text{neither exposed}}\bigg) - \bigg[ \bigg(\underbrace{\mathbb{E}[Y(1,0)]}_{\text{only A exposed}} - \underbrace{\mathbb{E}[Y(0,0)]}_{\text{neither exposed}}\bigg) + \bigg(\underbrace{\mathbb{E}[Y(0,1)]}_{\text{only B exposed}} - \underbrace{\mathbb{E}[Y(0,0)]}_{\text{neither exposed}} \bigg)\bigg] \neq 0 $$

This equation simplifies to

$$ \underbrace{\mathbb{E}[Y(1,1)]}_{\text{joint exposure}} - \underbrace{\mathbb{E}[Y(1,0)]}_{\text{only A exposed}} - \underbrace{\mathbb{E}[Y(0,1)]}_{\text{only B exposed}} + \underbrace{\mathbb{E}[Y(0,0)]}_{\text{neither exposed}} \neq 0 $$

A positive value would indicate evidence for additive interaction. A
negative value would indicate evidence for sub-additive interaction. A
value near zero would imply no reliable evidence for interaction.

```{tikz}
#| label: fig-dag-interaction
#| fig-cap: "This diagram presents the individual and joint effects of two exposures, A and B, on outcome Y. We assume that A and B are causally independent. If either exposure affects the other, then we may conduct effect-modification analysis or mediation analysis, but we should avoid causal interaction analysis. The diagram includes confounders L and W. Control for these confounders is necessary to close the backdoor paths that relate each exposure, A and B, to the outcome. Each exposure has equal status in our model: Y(a,b) = Y(b,a). The red path denotes paths of confounding."
#| out-width: 80%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw]

\node [rectangle, draw=white] (LA) at (0, .5) {L$_{0}$};
\node [rectangle, draw=white] (LB) at (0, -.5) {W$_{0}$};
\node [rectangle, draw=white] (A) at (2, .5) {A$_{1}$};
\node [rectangle, draw=white] (B) at (2, -.5) {B$_{1}$};
\node [rectangle, draw=white] (Y) at (5, 0) {Y$_{2}$};


\draw [-latex, draw=red] (LA) to (A);
\draw [-latex, draw=red] (LB) to (B);
\draw [-latex, draw=red, bend left] (LA) to (Y);
\draw [-latex, draw=red, bend right] (LB) to (Y);

%\draw [-latex, draw=black] (A) to (Y);
%\draw [-latex, draw=black] (B) to (Y);


\end{tikzpicture}

```

@fig-dag-interaction clarifies the need to evaluate two sources of counfounding, one for each intervention ($A$ and $B$). The graph resembles others we have considered. By adjusting for $L_{0}$ we obtain an unbiased estimate of the $A\to Y$ path. By adjusting for $W_{0}$ we obtain an unbiased estimate of the $B\to Y$ path. As indicated in @fig-dag-interaction-solved, we  must condition on both $L_{0}$ and $W_{0}$ to identify causal interaction conceived as a joint interaction. 

An important complication is that evidence for causal interaction may differ depending on the measurement scale one chooses to assess it [@vanderweele2014,@vanderweele2012]. Evidence for the strength of a causal effect estimate for interaction in the presence of effect-modification will differ depending on whether the effect is measured on the ratio scale as opposed to the difference scale (see: @vanderweele2014, who recommends using the causal difference scale for most policy settings.)

```{tikz}
#| label: fig-dag-interaction-solved
#| fig-cap: "We adjust for confounding in causal interaction analysis by adjusting for all confounders of the A to Y path as well as all for the B to Y path. The box over the confounders indicates the biasing paths are closed."
#| out-width: 80%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw]

\node [rectangle, draw=black] (LA) at (0, .5) {L$_{0}$};
\node [rectangle, draw=black] (LB) at (0, -.5) {W$_{0}$};
\node [rectangle, draw=white] (A) at (2, .5) {A$_{1}$};
\node [rectangle, draw=white] (B) at (2, -.5) {B$_{1}$};
\node [rectangle, draw=white] (Y) at (5, 0) {Y$_{2}$};


\draw [-latex, draw=black] (LA) to (A);
\draw [-latex, draw=black] (LB) to (B);
\draw [-latex, draw=black, bend left] (LA) to (Y);
\draw [-latex, draw=black, bend right] (LB) to (Y);

%\draw [-latex, draw=black] (A) to (Y);
%\draw [-latex, draw=black] (B) to (Y);


\end{tikzpicture}

```

Again we arrange @fig-dag-interaction-solved to follow the assumed sequence of
causation. Doing so better clarifies demands for data quality -- the timing of the events must be ensured. Data collection should also draw on expert knowledge about how $A$ and $B$ may be related over time; measurements of $A$ and $B$ should be taken within intervals in which $A$ and $B$ are unlikely to affect each other.

#### 3.1.4 Interaction as effect-modification of a single intervention

```{tikz}
#| label: fig-dag-effect-modification
#| fig-cap: "A simple sequentially ordered graph depicting effect-modification. We are interested in G as an effect-modifier of A on Y. A must not affect G (although G may affect A, we do not suppose such an effect). The blue path indicates effect-modification of A by G. The red path indicates an open backdoor path. We draw a box around G to indicate that we are conditioning on G in our model. We are interested in estimating the effect of A on Y. We must close all backdoor paths between A and Y, in this case, by conditioning on L. We are not interested in the effect of double intervention of G and A. Hence, we do not need to condition on Z to close the backdoor path from G to Y."
#| out-width: 80%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw, emod/.style={rectangle, fill=blue!10},
emoddot/.style={circle,fill=blue!10,dotted}]

\node [rectangle, draw=white] (LA) at (0, .5) {L$_{0}$};
\node [emoddot, draw=white] (LG) at (-2, -.5) {Z};
\node [rectangle, draw=white] (A) at (2, .5) {A$_{1}$};
\node [emod, draw=blue] (G) at (0, -.5) {G};
\node [rectangle, draw=white] (Y) at (4, 0) {Y$_{2}$};


\draw [-latex, draw=red] (LA) to (A);
\draw [-latex, draw=blue] (LG) to (G);
\draw [-latex, draw=blue] (G) to (Y);
\draw [-latex, draw=red, bend left] (LA) to (Y);
\draw [-latex, draw=blue, bend right] (LG) to (Y);
\end{tikzpicture}
```

It is often scientifically interesting to consider whether treatment effects vary over levels of other variable without imagining a double intervention. We call a variable over which the treatment effect varies, an 'effect-modifier' or an 'effect-measure modifier.' We call the phenomenon of variation in the effect of the exposure over levels of a covariate, 'effect-modification,' or 'effect-measure modification' or 'treatment effect heterogeneity. The counterfactual contrasts required to estimate effect-modification differ from those of a joint intervention. Suppose $A$ is the treatment, $G$ is the modifier, and $Y$ is the outcome. effect-modification assesses whether the effect of $A$ on $Y$ is different across levels of $G$ (i.e., whether the effect of $A$ on $Y$ is different when $G = g1$ compared to when $G = g2$).

@fig-dag-effect-modification consider whether effect-modification of $A$ on $Y$ across levels of $G$. Because we are not interested in the causal effect of $G$ as such, but rather, how the effect of $A$ varies across $G$, we would not need to adjust $G$ by $Z$. However, as we shall consider in the next section, the presence and absence of effect-modification may depend on other variables in a causal network, as well as on which other variables investigators condition on in their models. To foreshadow, we suppose that $Z$, a parent of $G$, is an effect-modifier of $A$ on $Y$. Were we to include $Z$ in the model, the effect estimate for $G$ on $Y$ may be attenuated or erased. There is here no clear fact of the matter about whether and how much $G$ is an effect-modifier outside of researcher modelling decisions. I remind readers: *with absolute power comes absolute responsibility.*

To better understand the interest of effect-modification, again consider a study investigating whether beliefs in big Gods affect social complexity. Suppose we compare two distinct geographical groups: North American societies ($G=1$) and Continental societies ($G=2$). Suppose we want to examine the causal effect of changing the exposure from $A = 0$ to $A = 1$ within each group and then compare these effects across the groups. The relevant causal contrasts are given as follows:

1.  **Causal effect within North American societies (**$G=1$):
    $$\hat{\tau}_{g1} = \hat{\mathbb{E}}[Y(1)|G=1] - \hat{\mathbb{E}}[Y(0)|G=1]$$ 
    
Here, $\hat{\tau}_{g1}$ represents the estimated causal effect of changing the exposure from $A = 0$ to $A = 1$ within the North American societies.

2.  **Causal effect within Continental societies (**$G=2$):

    $$\hat{\tau}_{g2} = \hat{\mathbb{E}}[Y(1)|G=2] - \hat{\mathbb{E}}[Y(0)|G=2]$$

    Similarly, $\hat{\tau}_{g2}$ denotes the estimated causal effect for the Continental societies.

3.  **Comparing causal effects across groups**:

    $$\hat{\gamma} = \hat{\tau}_{g1} - \hat{\tau}_{g2}$$ 
    
The estimated quantity $\hat{\gamma}$ computes the difference in the causal estimands between the two groups. A nonzero $\hat{\gamma}$ indicates effect-modification, suggesting that the effect of changing the exposure differs between the two groups. If we were to observe that $\hat{\gamma} \neq 0$, this would provide evidence for variability in the effect of the exposure on the outcome in different groups. Note that the causal effect for one group might be indistinguishable from zero, and yet we might nevertheless find evidence for effect-modification if the comparison group exhibits reliably different responses from the contrast group that is indistinguishable from zero.

#### 3.1.5 Evidence for effect-modification is relative to inclusion of other variables in the model

The 'sharp-null hypothesis' states there is no effect of the exposure on
the outcome for any unit in the target population. Unless the 'sharp-null hypothesis' is false, there may be effect-modification. For any study worth conducting, we cannot evaluate whether the sharp-null hypothesis is false. If we could the experiment would be otiose. Therefore, we must assume the possibility of effect-modification. Notably, whether a variable is an effect-modifier also depends on which other variables are included in the model. That is, just as for the concept of a 'confounder', where a variable is an 'effect-modifier' cannot be stated without reference to an assumed causal order and an explicit statement about which other variables will be included in the model [@vanderweele2012].

@fig-eff-mod-rel presents a scenario in which the marginal association
between $A$ and $Y$ is unbiased. The exposure $A$ is unconditionally
associated with $Y$. Recall our convention $\boxedblue{G}$ denotes
effect-modification with conditioning and $\circleblue{Z}$ indicates
effect-modification without conditioning. This graph states that the
conditional association of $A$ on $Y$ varies within levels of
$\boxedblue{G}$ (which is conditioned on), and furthermore that $G$ is
an *effect-modifier by proxy* [@vanderweele2009distinction]. Here,
$\circleblue{Z}$ fully mediates the association of $G$ and $Y$. That is
$\circleblue{Z}$ causes both $G$ and $Y$, and $G$ has no causal effect
on $Y$.

```{tikz}
#| label: fig-eff-mod-rel
#| fig-cap: "Consider a randomised experiment. There is no confounding. Here, the marginal association between A and Y provides an unbiased estimate for the causal effect of A on Y. Does the conditional association of A on Y vary within levels of G? The causal diagram allows for a classification of G as an effect modifier of A on Y by proxy. G modifies A's effect on Y in virtue of G's relationship to Z, which, according to this graph, is a direct effect modifier for the effect of A on Y."
#| out-width: 80%
#| echo: false


\begin{tikzpicture}[{every node/.append style}=draw, emod/.style={rectangle, fill=blue!10,draw=blue, thick},
emoddot/.style={circle, fill=blue!10, draw=blue, dotted}]


\node [rectangle, draw=white] (A) at (0, 0) {A$_{1}$};
\node [rectangle, draw=white] (Y) at (2, 0) {Y$_{2}$};
\node [emoddot] (Z) at (-3,0) {Z};
\node [emod] (G) at (-1, 0) {G};

\draw [-latex, draw=black] (A) to (Y);
\draw [-latex, bend left, draw=blue] (Z) to (Y);
\draw [-latex, draw = blue] (Z) to (G);

\end{tikzpicture} 


```

@fig-dag-effect-modification-4 presents the same a randomised experiment
as in the previous causal diagram. We again assume that there is no
confounding of the marginal association between the exposure, $A$, and
the outcome, $Y$. However, suppose we were to adjust for $Z$ and ask,
does the conditional association of $A$ on $Y$ vary within levels of
$G$, after adjusting for $Z$? That is, does $G$ remain an
effect-modifier of the exposure on the outcome? @vanderweele2007 proved
that for effect-modification to occur, at least one other arrow besides
the treatment must enter into the outcome. According to
@fig-dag-effect-modification-4, the only arrow into $Y$ other than $A$
arrives from $Z$. Because $Y$ is independent of $G$ conditional on $Z$
we may infer that $G$ is no longer an effect modifier for the effect of
$A$ on $Y$. Viewed another way, $G$ no longer co-varies with $Y$
conditional on $Z$ and so cannot act as an effect-modifier.

```{tikz}
#| label: fig-dag-effect-modification-4
#| fig-cap: "Conditioning on Z renders G independent of Y. G is no longer an effect modifier after conditioning on Z because G is independent of Y. Although Z is an unconditional effect modifier, G is not."
#| out-width: 80%
#| echo: false


\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw, emod/.style={rectangle, fill=blue!10,draw=blue, thick},
squarednode/.style={rectangle, draw=blue!60, fill=red!20, very thick, minimum size=5mm}]
\node [rectangle, draw=white] (A) at (0, 0) {A$_{1}$};
\node [rectangle, draw=white] (Y) at (2, 0) {Y$_{2}$};
\node [emod] (Z) at (-3,0) {Z};
\node [rectangle, draw=white] (G) at (-1, 0) {G};

\draw [-latex, draw=black] (A) to (Y);
\draw [-latex, bend left, draw=blue] (Z) to (Y);
\draw [-latex, draw = black] (Z) to (G);

\end{tikzpicture} 


```

@fig-dag-effect-modification-5 presents the same a randomised experiment
as in the previous graph. If we do not condition on $B$, then $G$ will
not modify the effect of $A$ on $Y$ because $G$ will not be associated
with $Y$. However, if we were to condition on $B$, then both $B$ (an
effect modifier by proxy) and $G$ may become effect-modifiers for the
causal effect of $A$ on $Y$. In this setting, both $B$ and $G$ are
conditional effect-modifiers.

Note that casual graphs help us to evaluate classifications of
conditional and unconditional effect modifiers. They may also help to
clarify conditions in which conditioning on unconditional
effect-modifiers may remove conditional effect-modification. However we
cannot not tell from a causal diagram whether the ancestors of an
unconditional effect-modifier will be conditional effect-modifiers for
the effect of the exposure on the outcome; see: @vanderweele2007, also
@suzuki2013counterfactual. Causal diagrams express non-parametric
relations. I have adopted an off-label colouring convention to denote
instances of effect-modification to highlight possible pathways for
effect-modification, which may be relative to other variables in a
model.

```{tikz}
#| label: fig-dag-effect-modification-5
#| fig-cap: "Blue path denotes effect-modification for G by conditioning on B. Both B and G are conditional effect modifiers."
#| out-width: 80%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw, emod/.style={rectangle, fill=blue!10,draw=blue, thick},
emoddot/.style={circle, fill=blue!10, draw=blue, dotted}]

\node [rectangle, draw=white] (A) at (1, 0) {A$_{1}$};
\node [rectangle, draw=white] (Y) at (3, 0) {Y$_{2}$};
\node [emoddot, dotted, draw=blue] (Z) at (-2, 1) {Z};
\node [emod] (G) at (-2, -1) {G};
\node [emod] (B) at (-1,0) {B};

\draw [-latex, draw=black] (A) to (Y);
\draw [-latex, bend left, draw=blue] (Z) to (Y);
\draw [-latex, draw=blue] (Z) to (B);
\draw [-latex, draw=blue] (G) to (B);
\end{tikzpicture} 

```

@fig-dag-effect-modification-5b reveals the relativity of
effect-modification. If investigators do not condition on $B$, then $G$
cannot be a conditional effect-modifier because $G$ would then be
independent of $Z$ because $B$ is a collider. However, as we observed in
@fig-dag-effect-modification-5, conditioning on $B$, a collider, may
open a path for effect-modification of $G$ by $Z$. Both $B$ and $G$ are
conditional effect modifiers.

```{tikz}
#| label: fig-dag-effect-modification-5b
#| fig-cap: "Blue path denotes effect-modification. Here G is not an effect modifier because B, a common effect (collider) of G and Z, is not conditioned on. Any conditional effect modification for G would require conditioning on B, and not-conditioning on G. Otherwise G will be d-separated from Y."
#| out-width: 80%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw, emod/.style={rectangle, fill=blue!10,draw=blue},
emoddot/.style={circle, fill=blue!10, draw=blue, dotted}]

\node [rectangle, draw=white] (A) at (1, 0) {A$_{1}$};
\node [rectangle, draw=white] (Y) at (3, 0) {Y$_{2}$};
\node [emoddot, dotted, draw=blue] (Z) at (-2, 1) {Z};
\node [rectangle, draw = black] (G) at (-2, -1) {G};
\node [emoddot] (B) at (-1,0) {B};

\draw [-latex, draw=black] (A) to (Y);
\draw [-latex, bend left, draw=blue] (Z) to (Y);
\draw [-latex, draw=blue] (Z) to (B);
\draw [-latex, draw=black] (G) to (B);
\end{tikzpicture} 

```

```{tikz}
#| label: fig-dag-effect-modification-5c
#| fig-cap: "Blue path denotes effect-modification. Neither, G nor B are unconditional effect-modifiers for the effect of A on Y after Z is conditioned upon. If investigators condition on Z, the causal diagram implies they will not find evidence for effect-modification by B or G, which are conditionally independent of Y once Z is conditioned upon."
#| out-width: 80%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw, emod/.style={rectangle, fill=blue!10,draw=blue, thick},
emoddot/.style={circle, fill=blue!10, draw=blue, dotted}]

\node [rectangle, draw=white] (A) at (1, 0) {A$_{1}$};
\node [rectangle, draw=white] (Y) at (3, 0) {Y$_{2}$};
\node [emod, draw=blue] (Z) at (-2, 1) {Z};
\node [rectangle, draw = black] (G) at (-2, -1) {G};
\node [rectangle] (B) at (-1,0) {B};

\draw [-latex, draw=black] (A) to (Y);
\draw [-latex, bend left, draw=blue] (Z) to (Y);
\draw [-latex, draw=black] (Z) to (B);
\draw [-latex, draw=black] (G) to (B);
\end{tikzpicture} 

```

@fig-dag-effect-modification-5c considers the implications of
conditioning on $Z$, which is the only unconditional effect-modifier on
the graph. If $Z$ is measured, conditioning on $Z$ will remove
effect-modification for $B$ and $G$ because $B,G\coprod Y |Z$. This
examples again reveals the context dependency of effect-modification.
Here, causal diagrams are useful for clarifying features of dependent
and independent effect modification. For further discussion, see:
@suzuki2013counterfactual; @vanderweele2009distinction.





## OLD MATERIAL

## What is interaction? 



### What is it to compare causal effects in groups?




$$\hat{\gamma} = \overbrace{\big( \hat{E}[Y(a)|G=g] - \hat{E}[Y(a^{\prime})|G=g] \big)}^{\hat{\delta_g}} - \overbrace{\big(\hat{E}[Y(a^{\prime})|G=g^{\prime}]- \hat{E}[Y(a)|G=g^{\prime}]\big)}^{\hat{\delta_{g^{\prime}}}}$$




