{
  "hash": "5ac5ed08f713ecb58cd6db8ab295b3bb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Causal Effects of Religious Service Attendance on Charity and Volunteering: Evidence Using Novel Measures From A National Longitudinal Panel\"\nabstract: |\n   Causal investigations for the effects of religion on prosociality must be precise. One should articulate a specific causal contrast for a feature of religion, select appropriate prosociality measures, define the target population, gather time-series data, and, only after identification assumptions are met, conduct statistical and sensitivity analyses. Here, we examine three distinct interventions on religious service attendance (increase, decrease, maintain) in a longitudinal sample of 33,198 New Zealanders (years 2018 to 2021). Study 1 investigates effects of religious service on charitable contributions and volunteerism. Studies 2 and 3 investigate effects of religious service on the relative risks of *receiving* aid or financial support from others during the past week -- measures designed to minimise self-reporting bias. Across all studies, inferred causal effects are substantially less pronounced than observed cross-sectional associations. Nonetheless, regular attendance across the population would enhance charitable donations by 4% of the New Zealand Government's annual spending. This research underscores the essential role of formulating precise causal questions and recommends a workflow for answering them in the scientific study of cultural practices.\nkeywords:\n  - Causal Inference\n  - Charity\n  - Church\n  - Cooperation\n  - Cross-validation\n  - Machine Learning\n  - Nonparametric \n  - Religion\n  - Volunteering\neditor_options: \n  chunk_output_type: console\nformat:\n  plos-pdf:\n    sanitise: true\n    keep-tex: true\n    link-citations: true\n    colorlinks: true\n    documentclass: article\n    classoption: [single column]\n    lof: false\n    lot: false\n    geometry:\n      - top=30mm\n      - left=20mm\n      - heightrounded\n    header-includes:\n      - \\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}\ndate: last-modified\nexecute:\n  echo: false\n  warning: false\n  include: true\n  eval: true\nfontfamily: libertinus\nbibliography: /Users/joseph/GIT/templates/bib/references.bib\ncsl: /Users/joseph/GIT/templates/csl/camb-a.csl\n---\n\n\n\n\n\n\n\n\n\n## Introduction\n\nA central question in the scientific study of religion is whether religion fosters prosociality [@johnson2005; @norenzayan2016; @watts2016; @watts2015; @sosis2003cooperation; @whitehouse2023; @schloss2011evolutionary; @swanson1967; @decoulanges1903; @wheatley1971]. However, quantifying causal effects for religion, and many other social behaviours presents significant challenges. Investigators have limited scope to randomise supernatural beliefs, community worship, and personal prayer. On the other hand, valid causal inferences from non-experimental or observational data must combine high-resolution repeated-measures time-series data with robust methods for causal inference. Few studies meet this standard. Indeed, a recent survey of the religion and prosociality literature reveals that nearly all observational studies assessing links between prosociality and religion are associational @kelly2024religiosity. To our knowledge, studies that draw on longitudinal (panel) data have yet to appropriately leverage their repeated measures data to obtain reliable causal inferences.\n\nAn encouraging recent attempt to obtain valid causal inference is Major-Smith's thoughtful investigation of the relationships between religious attendance, beliefs, and affiliation on blood donations among pregnant women and their partners who were residents of Bristol, United Kingdom, in the early 1990s and participated in the Avon Longitudinal Study of Parents and Children, $N=13,477$ mothers and $N=13,424$ partners [@major2023exploring]. Major-Smith's study begins with a careful overview of the threats to causal inference from confounding and selection bias. Next, a series of cross-sectional regression analyses observe associations between the stated features of religion and self-reported blood donations in this Bristol cohort. Unfortunately, because the outcome is a retrospective question asked during pregnancy about past blood donations, the analysis cannot capitalise on the time-series data of the Avon panel. There is neither control for baseline measures of religion variables (the treatments) nor for baseline blood donations (the outcome), and the study cannot evaluate outcomes after initiation into religious service or its cessation. Although we may sometimes use cross-sectional associations to obtain credible suggestions about causality, we cannot typically attach causal interpretations, at least not without strong assumptions about the relative order and timing of events [@vanderweele2021can]. Indeed, below we report an analysis restricted to baseline New Zealand Attitudes and Values Study data that observes a 2.89 times overstatement of monthly vs zero charitable donations causal contrast and a 2.58 times overstatement of the monthly vs zero volunteering causal contrast. A virtue of @major2023exploring, however, is that the study makes its causal assumptions explicit, and provides several sensitivity analyses to frame its results.\n\n\nHere, to obtain causal inferences from time-series data, we leverage comprehensive panel data from 33,198 participants in the New Zealand Attitudes and Values Study from 2018-2021 to quantify the effects of clearly defined interventions in religious attendance across the population of New Zealanders on two features of prosociality: charitable financial donations and volunteering, measured by stated charitable donations and volunteering as well as by revealed measures of help received from the community. We define a causal effect as a quantitative contrast between mean outcomes for a population from pre-specified interventions. These outcomes are called “counterfactual” or “potential” outcomes, terms we use interchangeably [@rubin2005; @neyman1923; @robins1986; @pearl2009; @vanderlaan2018].[^theory] A fundamental challenge in observational studies is to ensure *balance* between the variables in interventions or “treatments” to be compared that might affect both treatment and the potential outcomes under treatment [@shiba2021using]. We call the state of imbalance *confounding*, and the strategy for ensuring balance, *confounding control.* In this study, we express the interventions on religious service as \"modified treatment policies\" [@haneuse2013estimation; @diaz2023lmtp; @díaz2021; @hoffman2023]. We obtain causal inferences by contrasting inferred population averages under different modified treatment policies.\n\n[^theory]: Philosophical disagreements about the meanings assigned to \"potential\" and \"counterfactual\" outcomes do not affect our use.\n\nOur initial causal contrast investigates: \"What would be the average difference across the New Zealand population if everyone attended religious services regularly (at least four times per month) versus if no one attended?\" This theoretical question simulates a hypothetical experiment with random assignment to regular or non-attendance. This contrast addresses the scientifically interesting all/none contrast that is common in experimental designs [@hernán2016]. \n\nA second causal contrast investigates: \"What would be the average difference across the New Zealand population if everyone attended religious services regularly compared with maintaining the status quo?\" Here, we contrast regular religious service and New Zealand society as it was at the end of the study (2021) without modification. This causal contrast may inform practical policies relevant to non-regular attendees who might start.\n\nOur third causal contrast examines: \"What would be the average difference across the New Zealand population if no one attended religious services compared with the status quo?\" Here, we contrast the loss of any religious service with New Zealand society as it was at the end of the study (2021), again without modification. This causal contrast may inform practical policies relevant to regular attendees who stop attending.\n\nAlthough the set of causal contrasts analysts might consider is unbounded, those we have selected address these specific scientific and policy interests.\n\nNote that our approach does not focus on testing specific hypotheses; instead, we aim to compute our pre-specified causal contrasts with high accuracy by combining appropriate time-series data and robust methods for causal inference [@hernan2024stating].\n\n\n## Method\n\n### Sample\n\nData were collected by the New Zealand Attitudes and Values Study (NZAVS), an annual longitudinal national probability panel study of social attitudes, personality, ideology, and health outcomes in New Zealand. Chris G. Sibley started the New Zealand Attitudes and Values Study in 2009, which has grown to include a community of over fifty researchers. Since its inception, The New Zealand Attitudes and Values Study has accumulated questionnaire responses from 72,910 New Zealand residents. The study operates independently of political or corporate funding and is based in a university setting. Data summaries for our study sample on all measures used in this study are found in **Appendices B-D**.  For more details about the New Zealand Attitudes and Values Study see: [OSF.IO/75SNB](https://doi.org/10.17605/OSF.IO/75SNB).\n\n### Treatment Indicator\n\nReligious service attendance is assessed in the New Zealand Attitudes and Values Study with the following questions:\n\n- *Do you identify with a religion and/or spiritual group? If yes...How many times did you attend a church or place of worship during the last month?*\n\nWe rounded responses to the nearest whole number. Because there were few responses greater than eight, we coded all above eight as eight (see *Appendix B*: we label this variable `religion_church_round`). Note that contrasts with responses greater than four were not intervened upon in the regular church service condition; we decided to ease the computational burden during estimation.\n\n### Measures of Prosociality\n\n\n**Study 1: Self-reported charity** The New Zealand Attitudes and Values Study includes two self-reported measures of pro-sociality:\n\n- Volunteering:\n  *\"Please estimate how many hours you spent doing each of the following things last week...Volunteer/charitable work\"*\n  \n- Annual charitable financial donations:\n  *\"How much money have you donated to charity in the last year?\"*\n\n\n**Study 2: Help received from others in the last week: *time* ** \n\nParticipants were asked:\n\n*\"Please estimate how much help you have received from the following sources in the last week.\"*\n\n- *Family...TIME (hours)*\n- *Friends...TIME (hours)*\n- *Community...TIME (hours)*\n\nOwing to the high variability of responses, we transformed responses into binary indicators: *0 = none/ 1 = any*.\n\n**Study 3: Help received from others in the last week: *money* ** \n\nSimilarly, participants were asked:\n\n*\"Please estimate how much help you have received from the following sources in the last week.\"*\n\n- *Family...MONEY (dollars)*\n- *Friends...MONEY (dollars)*\n- *Community...MONEY (dollars)*\n\nThese measures were also highly variable. Hence, we converted responses to binary indicators: *0 = none/ 1 = any*.\n\nStudies 2 and 3 aim to minimise self-presentation bias by using revealed measures of prosocial exposure. Our approach assumes that if religious institutions foster prosociality, the initiation of regular attendance --controlling for past religious service, past measures of the prosocial outcomes, and a rich array of demographic, personality, and health measures recorded at baseline --  will increase exposure to prosocial behaviours. Notably, our revealed measures of prosociality rely on stated help received are robust to self-presentation biases that might associate religious service attendance with indicators of prosociality in the absence of causation. Such an association could occur if initiation into treatment affected the subsequent error term of one or more of the outcomes we contrast. Note that we include baseline outcomes and treatments in all studies, which mitigates the threat of undirected correlated errors. \n\nWe provide comprehensive details of all measures in **Appendix A**.\n\n\n### Causal Interventions\n\nWe define three targeted causal contrasts (*causal estimands*) as interventions on prespecified modified treatment policies (refer to @haneuse2013estimation; @diaz2021nonparametric; @diaz2023lmtp). Let $A_t$ denote the treatment -- monthly frequency of religious service. There are three time points: $t\\in{0,1,2}$, where $t=0$ denotes the baseline wave, $t=1$, the treatment wave, and $t=2$ at the end of the study. $\\mathbf{d}(\\cdot)$ denotes a modified treatment policy $f_\\mathbf{d}$. When a treatment is fixed to a level defined by the modified treatment policy, perhaps contrary to a participant's observed level of treatment, we use the lowercase symbol $a_1$. Here, the functions defined by modified treatment policies $f_\\mathbf{d}$ are interventions that fix $A_1$ to $a_1$.\n\n1. **Regular Religious Service Treatment**: Administer regular religious service attendance to everyone in the adult population. If an individual's religious service attendance is below four times per month, shift to four; otherwise, maintain their current attendance:\n\n$$\n\\mathbf{d}^\\lambda (a_1) = \\begin{cases} 4 & \\text{if } a_1 < 4 \\\\ \na_1 & \\text{otherwise} \\end{cases}\n$$\n\n2. **Zero Religious Service Treatment**: Ensure no religious service attendance for everyone in the adult population of New Zealand. If an individual's religious service attendance is greater than zero, shift to zero; otherwise, make no change:\n\n$$\n\\mathbf{d}^\\phi (a_1) = \\begin{cases} 0 & \\text{if } a_1 > 0 \\\\ \na_1 & \\text{otherwise} \\end{cases}\n$$\n\n3. **Status Quo -- No Treatment**: Apply no treatment. Each expected mean outcome is calculated using each individual's natural (observed) value of religious service attendance.\n\n\n$$\n\\mathbf{d}(a_1) = a_1\n$$\n\n\n### Causal Contrasts\n\nFrom these policies, we compute the following causal contrasts.\n\n**Target Contrast A: 'Regular vs. Zero'**: How do the prosocial effects of a society with regular religious service attendance differ from those of a society with zero religious service attendance?\n\n$$ \\text{Regular Religious Service vs. Zero Religious Service} = E[Y(\\mathbf{d}^\\lambda) - Y(\\mathbf{d}^\\phi)] $$\n\nThis contrast simulates a scientifically interesting hypothetical experiment where we could randomise individuals to either regular religious service or none, assessing the differences in prosociality outcomes measured one year after the intervention.\n\n**Target Contrast B: 'Regular vs. Status Quo'**: How does a society with regular religious service attendance compare to its status quo?\n\n$$ \\text{Regular Religious Service vs. No Treatment} = E[Y(\\mathbf{d}^\\lambda) - Y(\\mathbf{d})] $$\n\nThis contrast reflects a policy-relevant hypothetical experiment examining the effect of transitioning to regular religious service if one does not already regularly attend, allowing us to quantitatively assess how much a society in which everyone attends would differ from a society in its current state. \n\n**Target Contrast C: 'Zero vs. Status Quo'**: What are the social consequences for society of zero religious service attendance compared to its status quo?\n\n$$ \\text{Zero Religious Service vs. No Treatment} = E[Y(\\mathbf{d}^\\phi) - Y(\\mathbf{d})] $$\n\nThis contrast investigates the policy implications of eliminating religious services entirely, questioning whether such a shift would meaningfully affect average levels of charitable donations and volunteering.\n\n### Identification Assumptions\n\nTo consistently estimate a causal effect, investigators must satisfy three assumptions:\n\n1. **Causal consistency:** potential outcomes must correspond with observed outcomes under the treatments in the data. Essentially, we assume potential outcomes do not depend on how the treatment was administered, conditional on measured covariates [@vanderweele2009; @vanderweele2013]. \n\n2. **Exchangeability**: given observed covariates, we assume treatment assignment is independent of the potential outcomes to be contrasted. In other words, there is \"no unmeasured confounding\" [@hernan2024WHATIF; @chatton2020].\n\n3. **Positivity:** every individual must have a non-zero chance of receiving the treatment, regardless of their covariate values @westreich2010. We evaluate this assumption in each study by examining changes in religious service attendance from baseline (NZAVS time 10) to the treatment wave (NZAVS time 11). For further discussion of these assumptions in the context of NZAVS studies, see @bulbulia2023a.\n\n\n### Target Population\n\nThe target population for this study comprises New Zealand residents as represented in the baseline wave of the New Zealand Attitudes and Values Study (NZAVS) during the years 2018-2019, weighted by New Zealand Census weights for age, gender, and ethnicity (refer to @sibley2021). The NZAVS is a national probability study designed to reflect the broader New Zealand population accurately. Despite its comprehensive scope, the NZAVS does have some limitations in its demographic representation. Notably, it tends to under-sample males and individuals of Asian descent while over-sampling females and Māori (the indigenous peoples of New Zealand). To address these disparities and enhance the accuracy of our findings, we apply New Zealand Census survey weights to the sample data. These weights adjust for variations in age, gender, and ethnicity to better approximate the national demographic composition [@sibley2021]. Survey weights were integrated into statistical models using the `weights` option in `lmtp` [@williams2021], following protocols stated in @bulbulia2024PRACTICAL.\n\n\n### Eligibility Criteria\n\nTo be included in the analysis of this study, participants needed to meet the following eligibility criteria:\n\n\n\n### Inclusion Criteria\n\n- Enrolled in the 2018 wave of the New Zealand Attitudes and Values Study (NZAVS time 10).\n- Missing covariate data at baseline was permitted, and the data was subjected to imputation methods to reduce bias. Only information obtained at baseline was used for such imputation (refer to @zhang2023shouldMultipleImputation).\nParticipants may have been lost to follow-up the end of study NZAVS time 12 if they met eligibility criteria at NZAVS time 11 (the treatment wave). We adjusted for attrition and non-response using censoring weights, described below.\n\n### Exclusion Criteria\n\n- Did not answer the religious service attendance question at New Zealand Attitudes and Values Study at time 10 (the baseline wave) and NZAVS time 11 (the treatment wave).\n\n\nA total of 33,198 individuals met these criteria and were included in the study.\n\n\n###  Causal Identification \n\n::: {#tbl-02}\n\n\n\n\n\n```{=latex}\n\\lmtptablethree\n```\n\n\n\n\n\nThis table presents three Single World Intervention Graphs (SWIGs), one for each treatment condition we compare. Note that we obtain robust confounding control by including baseline measures for both the treatments and outcomes (refer to  @vanderweele2020, protocols described in @bulbulia2024PRACTICAL).We recommend using SWIGs because they are more precise and general than standard causal diagrams (refer to @richardson2013swigsprimer).\n:::\n\n\n\n@tbl-02 presents three Single World Intervention Graphs (SWIGs) that describe our confounding control  (identification strategy) [@robins2010alternative; @richardson2013swigsprimer; @shpitser2022multivariate; @richardson2023nested; @richardson2023potential; @shpitser2016causal]. Our approach consistently applies the same identification strategy across all functions estimated in this study. Unlike standard causal diagrams, SWIGs allow us to *separately* read the factorisation of the conditional dependencies for the distribution of each set of counterfactual outcomes under each modified treatment policy [@richardson2013swigsprimer]. Note, that the natural value of the treatment $A$ is obtained both from its observed instances and from baseline historical data, including the baseline treatment. This method ensures that our analysis accurately captures the causal effects of flexible treatment regimes that rely on levels of religious service attendance at the treatment wave, while ensuring balance for each treatment function that we compare [@diaz2012population; @young2014identification; @diaz2021nonparametric]. \n\n\n### Confounding Control\n\nTo manage confounding in our analysis, we implement @vanderweele2019's *modified disjunctive cause criterion* by following these steps:\n\n  1. **Identified all common causes** of both the treatment and outcomes to ensure a comprehensive approach to confounding control.\n  2. **Excluded instrumental variables** that affect the exposure but not the outcome. Instrumental variables do not contribute to controlling confounding and can reduce the efficiency of the estimates.\n  3. **Included proxies for unmeasured confounders** affecting both exposure and outcome. According to the principles of d-separation, using proxies allows us to control for their associated unmeasured confounders indirectly.\n  4. **Controlled for baseline exposure** and **baseline outcome**. Both are used as proxies for unmeasured common causes, enhancing the robustness of our causal estimates.\n\n[Appendix B](#appendix-demographics) details the covariates we included for confounding control. These methods adhere to the guidelines provided in [@bulbulia2024PRACTICAL] and were pre-specified in our study protocol [https://osf.io/ce4t9/](https://osf.io/ce4t9/).\n\n\n\n### Missing Data\n\n\nTo mitigate bias from missing data, we implement the following strategies:\n\n**Baseline missingness**: we employed the `ppm` algorithm from the `mice` package in R [@vanbuuren2018] to impute missing baseline data. This method allowed us to reconstruct incomplete datasets by estimating a plausible value for missing observation. Because we could only pass one data set to the `lmtp`, we employed single imputation. About 2% of covariate values were missing at baseline. Eligibility for the study required fully observed baseline treatment measures as well as treatment wave treatment measures. Again, we only used baseline data to impute baseline missingness (refer to @zhang2023shouldMultipleImputation).\n\n**Outcome missingness**: to address confounding and selection bias arising from missing responses and panel attrition, we applied censoring weights obtained using nonparametric machine learning ensembles afforded by the `lmtp` package (and its dependencies) in R [@williams2021]. \n\n### Statistical Estimator\n\n<!-- We use a Sequentially Doubly-Robust (SDR) estimator designed for the analysis of longitudinal data within causal inference frameworks [@díaz2021]. The estimator is grounded in the principles of robust semi-parametric statistics and is characterised first by its sequential approach to handling time-varying treatments and outcomes and, secondly, its double robustness property. -->\n\n<!-- Fundamentally, the SDR estimator operates by iteratively regressing pseudo-outcomes on observed treatments and covariates at each time point, starting from the end of the observation period and proceeding backwards. This iterative process employs the concept of pseudo-outcomes, which are updated at each step based on the outcome of the regression, incorporating information from both the treatment mechanism and the outcome model. -->\n\n<!-- A key feature of the SDR estimator is its 'multiply robust' property, implying that the estimator remains consistent if, for each time point, either the model for the treatment assignment or the model for the outcome, conditional on past treatments and covariates, is correctly specified. This property significantly enhances the estimator's applicability to real-world scenarios such as ours, where model misspecification is a common challenge. Furthermore, the marriage of SDR and machine learning reduces the dependence of inference on restrictive modelling assumptions and introduces an additional layer of robustness. For further details see [@hoffman2022; @hoffman2023; @díaz2021]. Estimation was performed using the `lmtp` package [@williams2021].  -->\n\n\nWe perform statistical estimation using semi-parametric Targeted Learning, specifically a Targeted Minimum Loss-based Estimation (TMLE) estimator. TMLE is a robust method that combines machine learning techniques with traditional statistical models to estimate causal effects while providing valid statistical uncertainty measures for these estimates [@van2014targeted; @van2012targeted].\n\nTMLE operates through a two-step process that involves modelling both the outcome and treatment (exposure). Initially, TMLE employs machine learning algorithms to flexibly model the relationship between treatments, covariates, and outcomes. This flexibility allows TMLE to account for complex, high-dimensional covariate spaces *efficiently* without imposing restrictive model assumptions [@van2014discussion; @vanderlaan2011; @vanderlaan2018]. The outcome of this step is a set of initial estimates for these relationships.\n\nThe second step of TMLE involves \"targeting\" these initial estimates by incorporating information about the observed data distribution to improve the accuracy of the causal effect estimate. TMLE achieves this precision through an iterative updating process, which adjusts the initial estimates towards the true causal effect. This updating process is guided by the efficient influence function, ensuring that the final TMLE estimate is as close as possible, given the measures and data, to the targeted causal effect while still being robust to model-misspecification in either the outcome or the treatment model [@van2014discussion].\n\nAgain, a central feature of TMLE is its double-robustness property. If either the treatment model or the outcome model is correctly specified, the TMLE estimator will consistently estimate the causal effect. Additionally, we used cross-validation to avoid over-fitting, following the pre-stated protocols in @bulbulia2024PRACTICAL.  The integration of TMLE and machine learning technologies reduces the dependence on restrictive modelling assumptions and introduces an additional layer of robustness. For further details of the specific targeted learning strategy we favour, see [@hoffman2022; @hoffman2023; @díaz2021]. We perform estimation using the `lmtp` package [@williams2021]. We used the `superlearner` library for semi-parametric estimation with the predefined libraries `SL.ranger`, `SL.glmnet`, and `SL.xgboost` [@polley2023; @xgboost2023; @Ranger2017]. We created graphs, tables and output reports using the `margot` package [@margot2024]. \n\n\n\n### Sensitivity Analysis Using the E-value\n\nTo assess the sensitivity of results to unmeasured confounding, we report VanderWeele and Ding's \"E-value\" in all analyses [@vanderweele2017]. The E-value quantifies the minimum strength of association (on the risk ratio scale) that an unmeasured confounder would need to have with both the exposure and the outcome (after considering the measured covariates) to explain away the observed exposure-outcome association [@vanderweele2020; @linden2020EVALUE]. To evaluate the strength of evidence, we use the bound of the E-value 95% confidence interval closest to 1.\n\n\n### Scope of Interventions\n\nTo illustrate the magnitude of the shift interventions we contrast, we provide histograms in @fig-hist, that display the distribution of treatments during the treatment wave. @fig-hist *A*: The intervention for regular religious service, represented in these histograms, affects a larger portion of the sample than the zero religious service intervention. @fig-hist *B*: presents the intervention for zero religious service. It involves shifting a smaller portion of the sample than the regular religious service intervention. Again, the comparative analysis of the 'Regular' versus 'Zero' interventions addresses the scientifically intriguing question: what is the effect difference in a scenario where religious service is universal versus completely absent?  The intervention that increases attendance to regular service levels from the status quo allows us to consider the potential costs and benefits of widespread religious practice across society. The intervention that eliminates religious service allows us to consider the potential costs and benefits of the widespread loss of religious practice across society.\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![This figure shows a histogram of responses to religious service frequency in the baseline + 1 wave. Responses above eight were assigned to eight, and values were rounded to the nearest whole number. The red dashed line shows the population average. (A) Responses in the gold bars are shifted to four on the Regular Religious Service intervention. All those responses in grey (four and above) remain unchanged. (B) On the zero-intervention, responses in the blue bars denote those shifted under the zero-intervention treatment.](psyc_434_manuscript_template_files/figure-html/fig-hist-1.png){#fig-hist width=960}\n:::\n:::\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n### Evidence for Change in the Treatment Variable\n\n@tbl-transition clarifies the change in the treatment variable from the baseline wave to the baseline + 1 wave across the sample.  Assessing change in a variable is essential for evaluating the positivity assumption and recovering evidence for the incident exposure effect of the treatment variable [@vanderweele2020; @danaei2012; @hernan2024WHATIF]. We find that state 4 (weekly attendance) and state 0 present the highest overall. However, movement between these states reveals they are not deterministic. States 1, 2, 3, and 5 exhibit more frequent jumps in and out of these states, suggesting lower stability and/or measurement error.  \n\n\n\n\n\n\n::: {#tbl-transition .cell tbl-cap='This transition matrix captures stability and change in religious service between the baseline and treatment wave. Each cell in the matrix represents the count of individuals transitioning from one state to another. The rows correspond to the state at baseline (From), and the columns correspond to the state at the treatment wave (To). **Diagonal entries** (in **bold**) signify the number of individuals who remained in their initial state across both waves. **Off-diagonal entries** signify the transitions of individuals from their baseline state to a different state in the treatment wave. A higher number on the diagonal relative to the off-diagonal entries in the same row indicates greater stability in a state. Conversely, higher off-diagonal numbers suggest more frequent shifts in the sample from the baseline state to other states.'}\n::: {.cell-output-display}\n\n\n|  From   |  State 0  | State 1 | State 2 | State 3 | State 4 | State 5 | State 6 | State 7 | State 8 |\n|:-------:|:---------:|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|\n| State 0 | **26762** |   405   |   174   |   71    |   126   |   26    |   13    |    8    |   68    |\n| State 1 |    647    | **235** |   85    |   44    |   46    |    5    |    2    |    3    |   10    |\n| State 2 |    236    |   105   | **188** |   104   |   96    |   12    |   13    |    2    |   21    |\n| State 3 |    112    |   54    |   110   | **164** |   173   |   18    |    8    |    4    |   15    |\n| State 4 |    150    |   71    |   127   |   205   | **881** |   124   |   64    |   16    |   91    |\n| State 5 |    24     |    7    |   17    |   17    |   145   | **61**  |   25    |    7    |   33    |\n| State 6 |    14     |    5    |   13    |   17    |   84    |   22    | **29**  |    5    |   37    |\n| State 7 |     9     |    0    |    6    |    3    |   16    |    6    |    9    |  **6**  |   19    |\n| State 8 |    74     |   14    |   17    |   14    |   105   |   34    |   42    |   17    | **351** |\n\n\n:::\n:::\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n## Results\n\n### Study 1: Causal Effects of Regular Church Attendance on Self-Reported Volunteering and Self-Reported Volunteering and Donations\n\n#### Regular Religious Service vs. Zero Treatment Contrast for Donations and Volunteering\n\nResults for the treatment contrasts between Regular Religious Service and Zero Religious Service, focusing on self-reported volunteering and charitable donations, are displayed in @fig-1_1 *A* and @tbl-1_1. These results are measured on the difference scale.\n\n\n\n\n\n\n\n\n::: {#tbl-1_1 .cell tbl-cap='This table reports the results of model estimates for the causal effects of a universal gain of weekly religious service vs. a universal loss of weekly religious service on reported charitable behaviours at the end of the study. Contrasts are expressed in standard deviation units.'}\n::: {.cell-output-display}\n\n\n|                | E[Y(1)]-E[Y(0)]| 2.5 %| 97.5 %| E_Value| E_Val_bound|\n|:---------------|---------------:|-----:|------:|-------:|-----------:|\n|donations       |           0.132| 0.102|  0.161|   1.507|       1.426|\n|hours volunteer |           0.123| 0.090|  0.156|   1.482|       1.389|\n\n\n:::\n:::\n\n\n\n\n\n\nFor 'donations', the effect estimate is 0.132 [0.102, 0.161]. The E-value for this estimate is 1.507, with a lower bound of 1.426. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.426 to negate the observed effect. Weaker associations would not overturn it. We infer **evidence for causality**.  On the data scale, this intervention represents a difference of **NZD 656.58 per adult per year** in charitable giving compared with the zero attendance intervention.\n\n\nThe effect estimate for 'hours volunteer' is 0.123 [0.09, 0.156]. The E-value for this estimate is 1.482, with a lower bound of 1.389. We infer **evidence for causality**. On the data scale, this intervention represents a difference of **NZD 30.21 minutes** per adult per week in volunteering compared with the zero attendance intervention.\n\n\n#### Regular Religious Service vs. Status Quo Treatment Contrast for Donations and Volunteering\n\n@fig-1_1 *B* and @tbl-1_2 present results for the treatment contrasts between Regular Religious Service and Status Quo, focusing on self-reported volunteering and charitable donations. These results are measured on the difference scale.\n\n\n\n\n\n\n\n::: {#tbl-1_2 .cell tbl-cap='This table reports results of model estimates for the causal effects of a universal gain of weekly religious service vs. the status quo on reported charitable behaviours at the end of the study. Contrasts are expressed in standard deviation units.'}\n::: {.cell-output-display}\n\n\n|                | E[Y(1)]-E[Y(0)]| 2.5 %| 97.5 %| E_Value| E_Val_bound|\n|:---------------|---------------:|-----:|------:|-------:|-----------:|\n|donations       |           0.121| 0.102|  0.140|   1.477|       1.422|\n|hours volunteer |           0.095| 0.066|  0.123|   1.404|       1.317|\n\n\n:::\n:::\n\n\n\n\n\n\nFor 'donations', the effect estimate is 0.121 [0.102, 0.14]. The E-value for this estimate is 1.477, with a lower bound of 1.422. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.422 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**. On the data scale, this intervention represents an increase of **NZD 601.87 per adult per year** in expected charitable giving over the status quo.\n\n\nFor 'hours volunteer', the effect estimate is 0.095 [0.066, 0.123]. The E-value for this estimate is 1.404, with a lower bound of 1.317. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.317 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.  On the data scale, this intervention represents an increase of **23.33 minutes ** per adult per week in hours volunteering over the status quo.\n\n\n#### Zero Religious Service vs. The Status Quo Treatment Contrast for Donations and Volunteering\n\n@fig-1_1 *C* and @tbl-1_3 present results for the treatment contrasts between Zero Religious Service and Status Quo, focusing on self-reported volunteering and charitable donations. These results are measured on the difference scale.\n\n\n\n\n\n\n\n::: {#tbl-1_3 .cell tbl-cap='This table reports the results of model estimates for the causal effects of a universal loss of weekly religious service vs. the status quo on reported charitable behaviours at the end of the study. Contrasts are expressed in standard deviation units.'}\n::: {.cell-output-display}\n\n\n|                | E[Y(1)]-E[Y(0)]|  2.5 %| 97.5 %| E_Value| E_Val_bound|\n|:---------------|---------------:|------:|------:|-------:|-----------:|\n|donations       |          -0.011| -0.029|  0.008|   1.111|       1.000|\n|hours volunteer |          -0.028| -0.042| -0.014|   1.189|       1.128|\n\n\n:::\n:::\n\n\n\n\n\n\n\nFor 'donations', the effect estimate is -0.011 [-0.029, 0.008]. The E-value for this estimate is 1.111, with a lower bound of 1. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1 to negate the observed effect. Weaker confounding would not overturn it. We infer that **the evidence for causality is not reliable**. On the data scale, this intervention represents a difference of NZD -54.72 per adult per year in charitable giving compared to the status quo. Still, again, this effect is not reliable.\n\n\nThe effect estimate for 'hours volunteer' is -0.028 [-0.042, -0.014]. The E-value for this estimate is 1.189, with a lower bound of 1.128. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.128 to negate the observed effect. Again, weaker confounding would not overturn it. We infer **evidence for causality**. **On the data scale, this intervention represents a difference of -6.88 in volunteering minutes compared with the status quo.**\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![This figure graphs the results of model estimates for the causal effects of the three causal contrasts of interest on reported charitable behaviours at the study's end. The causal contrasts are: (A) Regular vs. Zero Religious Service, (B) Regular Religious Service vs. Status Quo, and (C) Zero  Religious Service vs. Status Quo. Contrasts are expressed in standard deviation units.](psyc_434_manuscript_template_files/figure-html/fig-1_1-1.png){#fig-1_1 width=960}\n:::\n:::\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n### Study 2: Causal Effects of Regular Church Attendance on Support Received From Others -- Time\n\n#### Regular vs. Zero Causal Treatment Contrast for Time Received From Others\n\n\n@fig-study2 *A* and @tbl-study2A present results for the treatment contrasts between Regular Religious Service and Zero, focusing on voluntary help received from others during the past week (yes/no). These results are measured on the risk ratio scale.\n\n\n\n\n\n\n\n::: {#tbl-study2A .cell tbl-cap='This table reports the results of model estimates for the causal effects of a universal gain of weekly religious service vs. a universal loss of weekly religious service on voluntary help received from others during the past week (yes/no) at the end of the study. Contrasts are expressed on the risk ratio scale.'}\n::: {.cell-output-display}\n\n\n|                     | E[Y(1)]/E[Y(0)]| 2.5 %| 97.5 %| E_Value| E_Val_bound|\n|:--------------------|---------------:|-----:|------:|-------:|-----------:|\n|family gives time    |           0.950| 0.901|  1.003|   1.288|       1.000|\n|friends give time    |           1.187| 1.108|  1.271|   1.658|       1.454|\n|community gives time |           1.378| 1.231|  1.541|   2.100|       1.764|\n\n\n:::\n:::\n\n\n\n\n\n\nFor 'community gives time', the effect estimate is 1.378 [1.231, 1.541]. The E-value for this estimate is 2.1, with a lower bound of 1.764. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.764 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\nFor 'friends give time', the effect estimate is 1.187 [1.108, 1.271]. The E-value for this estimate is 1.658, with a lower bound of 1.454. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.454 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\nFor 'family gives time', the effect estimate is 0.95 [0.901, 1.003]. The E-value for this estimate is 1.288, with a lower bound of 1. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1 to negate the observed effect. Weaker confounding would not overturn it. We infer **that evidence for causality is not reliable**.\n\n#### Regular Religious Service vs. Status Quo Treatment Contrast for Time Received From Others\n\n@fig-study2*B* and @tbl-2-2 present results for the treatment contrasts between Regular Religious Service and Status Quo, focusing on voluntary help received from others during the past week (yes/no). These results are measured on the risk ratio scale.\n\n\n\n\n\n\n::: {#tbl-2-2 .cell tbl-cap='This table reports the results of model estimates for the causal effects of a universal gain of weekly religious service vs. the status quo on voluntary help received from others during the past week (yes/no) at the end of the study. Contrasts are expressed on the risk ratio scale.'}\n::: {.cell-output-display}\n\n\n|                     | E[Y(1)]/E[Y(0)]| 2.5 %| 97.5 %| E_Value| E_Val_bound|\n|:--------------------|---------------:|-----:|------:|-------:|-----------:|\n|family gives time    |           0.958| 0.913|  1.006|   1.258|       1.000|\n|friends give time    |           1.128| 1.061|  1.199|   1.508|       1.315|\n|community gives time |           1.289| 1.174|  1.415|   1.899|       1.626|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nFor 'community gives time', the effect estimate is 1.289 [1.174, 1.415]. The E-value for this estimate is 1.899, with a lower bound of 1.626. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.626 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\nFor 'friends give time', the effect estimate is 1.128 [1.061, 1.199]. The E-value for this estimate is 1.508, with a lower bound of 1.315. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.315 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\nFor 'family gives time', the effect estimate is 0.958 [0.913, 1.006]. The E-value for this estimate is 1.258, with a lower bound of 1. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1 to negate the observed effect. Weaker confounding would not overturn it. We infer **that evidence for causality is not reliable**.\n\n\n#### Zero Religious Service vs. Status Quo Treatment Contrast for Time Received From Others\n\n@fig-study2 *C* and @tbl-2_3 present results for the treatment contrasts between Zero Religious Service and Status Quo, focusing on voluntary help received from others during the past week (yes/no). These results are measured on the risk ratio scale.\n\n\n\n\n\n\n\n::: {#tbl-2_3 .cell tbl-cap='This table reports results of model estimates for the causal effects of a universal loss of weekly religious service vs. the status quo on voluntary help received from others during the past week (yes/no) at the end of the study. Contrasts are expressed on the risk ratio scale.'}\n::: {.cell-output-display}\n\n\n|                     | E[Y(1)]/E[Y(0)]| 2.5 %| 97.5 %| E_Value| E_Val_bound|\n|:--------------------|---------------:|-----:|------:|-------:|-----------:|\n|family gives time    |           1.008| 0.991|  1.026|   1.098|       1.000|\n|friends give time    |           0.950| 0.928|  0.973|   1.288|       1.197|\n|community gives time |           0.936| 0.889|  0.985|   1.339|       1.140|\n\n\n:::\n:::\n\n\n\n\n\n\nFor 'family gives time', the effect estimate is 1.008 [0.991, 1.026]. The E-value for this estimate is 1.098, with a lower bound of 1. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1 to negate the observed effect. Weaker confounding would not overturn it. We infer **that evidence for causality is not reliable**.\n\nFor 'friends give time', the effect estimate is 0.95 [0.928, 0.973]. The E-value for this estimate is 1.288, with a lower bound of 1.197. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.197 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\nFor 'community gives time', the effect estimate is 0.936 [0.889, 0.985]. The E-value for this estimate is 1.339, with a lower bound of 1.14. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.14 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![This figure reports the results of model estimates for the three causal contrasts of interest on help received from others during the past week (yes/no). The causal contrasts are (A) Regular vs. Zero Religious Service, (B) Regular Religious Service vs. Status Quo, and (C) Zero  Religious Service vs. Status Quo. Contrasts are expressed on the risk ratio scale.](psyc_434_manuscript_template_files/figure-html/fig-study2-1.png){#fig-study2 width=960}\n:::\n:::\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n### Study 3: Causal Effects of Regular Church Attendance on Support Received From Others -- Money\n\n#### Regular vs. Zero Causal Contrast on Money Received From Others\n\n@fig-study_3 *A* and @tbl-3_1 present results for the treatment contrasts between Regular Religious Service and Zero, focusing on money received from others during the past week (yes/no). These results are measured on the risk ratio scale.\n\n\n\n\n\n\n\n::: {#tbl-3_1 .cell tbl-cap='This table reports the results of model estimates for the causal effects of a universal gain of weekly religious service vs. a universal loss of weekly religious service on financial help received from others during the past week (yes/no) at the end of the study. Contrasts are expressed on the risk ratio scale.'}\n::: {.cell-output-display}\n\n\n|                      | E[Y(1)]/E[Y(0)]| 2.5 %| 97.5 %| E_Value| E_Val_bound|\n|:---------------------|---------------:|-----:|------:|-------:|-----------:|\n|family gives money    |           1.137| 1.028|  1.258|   1.532|       1.198|\n|friends give money    |           1.137| 0.964|  1.342|   1.532|       1.000|\n|community gives money |           1.376| 1.112|  1.703|   2.095|       1.465|\n\n\n:::\n:::\n\n\n\n\n\n\n\nFor 'community gives money', the effect estimate is 1.376 [1.112, 1.703]. The E-value for this estimate is 2.095, with a lower bound of 1.465. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.465 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\nFor 'family gives money', the effect estimate is 1.137 [1.028, 1.258]. The E-value for this estimate is 1.532, with a lower bound of 1.198. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.198 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\nFor 'friends give money', the effect estimate is 1.137 [0.964, 1.342]. The E-value for this estimate is 1.532, with a lower bound of 1. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1 to negate the observed effect. Weaker confounding would not overturn it. We infer **that evidence for causality is not reliable**.\n\n\n#### Regular vs. Status Quo Causal Contrast on Money Received From Others\n\n@fig-study_3 *B* and @tbl-3_2 present results for the treatment contrasts between Regular Religious Service and Status Quo, focusing on money received from others during the past week (yes/no). These results are measured on the risk ratio scale.\n\n\n\n\n\n\n\n::: {#tbl-3_2 .cell tbl-cap='This table reports the results of model estimates for the causal effects of a universal gain of weekly religious service vs. the status quo on financial help received from others during the past week (yes/no) at the end of the study. Contrasts are expressed on the risk ratio scale.'}\n::: {.cell-output-display}\n\n\n|                      | E[Y(1)]/E[Y(0)]| 2.5 %| 97.5 %| E_Value| E_Val_bound|\n|:---------------------|---------------:|-----:|------:|-------:|-----------:|\n|family gives money    |           1.130| 1.037|  1.232|   1.513|       1.233|\n|friends give money    |           1.041| 0.951|  1.139|   1.248|       1.000|\n|community gives money |           1.254| 1.098|  1.432|   1.818|       1.426|\n\n\n:::\n:::\n\n\n\n\n\n\nFor 'community gives money', the effect estimate is 1.254 [1.098, 1.432]. The E-value for this estimate is 1.818, with a lower bound of 1.426. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.426 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\nFor 'family gives money', the effect estimate is 1.13 [1.037, 1.232]. The E-value for this estimate is 1.513, with a lower bound of 1.233. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.233 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\nFor 'friends give money', the effect estimate is 1.041 [0.951, 1.139]. The E-value for this estimate is 1.248, with a lower bound of 1. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1 to negate the observed effect. Weaker confounding would not overturn it. We infer **that evidence for causality is not reliable**.\n\n#### Zero vs. Status Quo Causal Contrast on Money Received From Others\n\n@fig-study_3 *C* and @tbl-3_3 present results for the treatment contrasts between Zero Religious Service and Status Quo, focusing on money received from others during the past week (yes/no). These results are measured on the risk ratio scale.\n\n\n\n\n\n\n\n\n::: {#tbl-3_3 .cell tbl-cap='Table reports results of model estimates for the causal effects of a universal loss of weekly religious service vs. the status quo on financial help received from others during the past week (yes/no) at the end of study. Contrasts are expressed on the risk ratio scale.'}\n::: {.cell-output-display}\n\n\n|                      | E[Y(1)]/E[Y(0)]| 2.5 %| 97.5 %| E_Value| E_Val_bound|\n|:---------------------|---------------:|-----:|------:|-------:|-----------:|\n|family gives money    |           0.993| 0.953|  1.035|   1.091|           1|\n|friends gives money   |           0.915| 0.809|  1.036|   1.412|           1|\n|community gives money |           0.911| 0.796|  1.042|   1.425|           1|\n\n\n:::\n:::\n\n\n\n\n\n\n\nFor 'family gives money', the effect estimate on the risk ratio scale is 0.993 [0.953, 1.035]. The E-value for this estimate is 1.091, with a lower bound of 1. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1 to negate the observed effect. Weaker confounding would not overturn it. We infer **that evidence for causality is not reliable**.\n\nFor 'friends give money', the effect estimate on the risk ratio scale is 0.915 [0.809, 1.036]. The E-value for this estimate is 1.412, with a lower bound of 1. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1 to negate the observed effect. Weaker confounding would not overturn it. We infer **that evidence for causality is not reliable**.\n\nFor 'community gives money', the effect estimate on the risk ratio scale is 0.911 [0.796, 1.042]. The E-value for this estimate is 1.425, with a lower bound of 1. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1 to negate the observed effect. Weaker confounding would not overturn it. We infer **that evidence for causality is not reliable**.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![This figure reports the results of model estimates for the three causal contrasts of interest on help received from others during the past week (yes/no). The causal contrasts are: (A) Regular vs. Zero Religious Service (B) Regular Religious Service vs. Status Quo; (C) Zero  Religious Service vs. Status Quo. Contrasts are expressed on the risk ratio scale.](psyc_434_manuscript_template_files/figure-html/fig-study_3-1.png){#fig-study_3 width=960}\n:::\n:::\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n### Additional Study: Comparison of Causal Inference Results with Cross-Sectional Regressions\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nTo better evaluate the contributions of our methodology to current practice, we conducted a series of cross-sectional analyses using the baseline wave data. We quantified the statistical associations between religious service attendance and our focal prosocial outcomes. We included all regression covariates from the causal models (including sample weights) for each analysis, obviously omitting the outcome measured at baseline, i.e. the response variable.\n\n**Cross-sectional volunteering result**: the change in expected hours of volunteer work for a one-unit increase in religious service attendance is b = 0.31; (95% CI 0.28, 0.34). Multiplying this by 4.2 gives a monthly estimate of 77.95 minutes. This result is 2.58 per cent greater than the effect estimated from the 'regular vs. zero' causal contrast, indicating an **overstatement in the cross-sectional regression model.**\n\n**Cross-sectional charitable donations result**: The coefficient for religious service on annual charitable donations suggests a change in expected donation amount per unit increase in attendance is: b = 451; (95% CI 408, 494). When adjusted to a monthly rate by multiplying by 4.2, this value equals NZ Dollars 1894.45. It is 2.89 per cent greater than our causal contrast estimate, again indicating **overstatement in the cross-sectional regression model.**\n\nFor Studies 2 and 3, which focus on community help received, we adjusted our analysis for the non-collapsibility of odds ratios by assuming a Poisson distribution for the outcome variables, obtaining a rate ratio that approximates a risk ratio [@huitfeldt2019collapsibility;@vanderweele2020]:\n\n**Cross-sectional community assistance received result: Time**: the exponentiated change in expectation for a one-unit change in religious service attendance is b = 1.17; (95% CI 1.14, 1.19) approximate risk rate ratio. The monthly rate ratio derived by multiplying this coefficient by 4.2 is 1.921. This estimate is 1.39 per cent greater than the 'regular vs. zero' causal estimate, pointing to **overstatement in the cross-sectional regression model.**\n\n**Cross-sectional community assistance received result: Money**: similarly, the exponentiated change for money received yields an approximate risk ratio of b = 1.18; (95% CI 1.08, 1.27). The monthly risk ratio, after adjustment, is 1.996. This rate ratio is 1.45 per cent greater than the causal estimate, again revealing an **overstatement in the cross-sectional regression model.**\n\n*These findings underscore that the results of cross-sectional regressions, although suggestive, can considerably diverge from those obtained from the causal analysis of panel data.*\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n### What is the \"Cash Value\" of Religious Service Attendance for Charitable Donations in New Zealand? \n\n\n\n\n\n\n\n\n\n\n\n\n\nWe leveraged results to estimate the approximate economic value of religious service attendance under different scenarios— 'Regular Religious Service', 'Zero Religious Service', and the 'Status Quo', focusing on charitable donations.\n\n- **Regular Religious Service**: an increase in religious service attendance yields an individual average donation sum of **NZD 1638.98.**\n- **Zero Religious Service**: Reducing religious service attendance to zero yields an average donation sum of **NZD 984.59.**\n- **Status Quo**: the expected individual average donation sum is currently **NZD 1037.14.**\n\nWith 3,989,000 adult residents in New Zealand in 2021:[^pop] \n\n- Multiplying the adult population by the average donation sum gives a status quo national estimate for charitable giving of **NZD 4,137,151,460.** \n- The net gain to charity from country-wide regular attendance at religious services, compared to the status quo, is **NZD 2,400,739,760.**\n- Conversely, although the net cost to charity from a complete cessation of regular religious service attendance is NZD -209,621,950, recall the confidence interval crosses zero, and this effect is not reliable.\n\nTo provide context, consider these economic consequences against the New Zealand government’s annual budget in year outcomes were measured (2021-2022) is NZD 57,976,000,000\n\n\n- **The expected gain from a nationwide adoption of regular religious service represents 4.1 percent of New Zealand's annual government budget 2021.**\n- We do not obtain a reliable effect from the loss intervention.\n\n[^pop]: [National Population Estimates at 30 June 2021](https://www.stats.govt.nz/information-releases/national-population-estimates-at-30-june-2021)\n[^source]: [Budget 2021](https://www.treasury.govt.nz/publications/budgets/budget-2021)\n\nThus, focussing on the individual-level and aggregating effects across the adult population, the counterfactual scenario in which all New Zealand adults regularly attend religious services projects a substantial increase in society-wide charitable support compared to the status quo, one year after the intervention. \n\nHowever, suppose New Zealand were to experience a complete cessation of religious service attendance. We do not find evidence that the landscape of charitable giving would change from its current state one year later.[^noteloss]\n\n[^noteloss]: We emphasise that failure to rule out an effect is not the same as ruling it out. The relatively low levels of religious service attendance in New Zealand mutes differences in expected giving. In our view, some amount of charity is always better than none. We do not devalue any form of charitable giving. Furthermore, our population-wide estimates for the aggregated effects of *religious behaviour* do not clarify the effects of gaining or losing *religious institutions*; our analysis reflects the contributions made by those participating in religious institutions.\n\n## Discussion \n\n### Considerations\n\nFirst, as stated above, our causal inferences turn on three assumptions, which are worth revisiting: \n\n(i). **Unmeasured confounding**: although we employ robust methods for causal inference, our results depend on the effectiveness of our strategy to control for confounding. Our sensitivity analyses address the potential impacts of unmeasured confounders. Nevertheless, the presence and influence of such confounders are uncertain and unverifiable from our data.\n\n(ii). **Causal consistency**: the observed outcomes must correspond to the counterfactual treatments contrasted. Although \"religious service attendance\" may appear conditionally independent of the outcomes given baseline covariates, interpreting these interventions remains challenging. \"Religious service attendance\" varies widely, encompassing everything from informal gatherings at homes to formal services in cathedrals across New Zealand's religious diversity. This type of \"treatment\" does not mirror a straightforward medical intervention like a vaccine. The heterogeneity of \"religious service\" limits the clarity of our results, an issue no amount of data or analysis can resolve because \"religious service\" reflects a broad spectrum of community activities.\n\n(iii). **Positivity**: we have confirmed that religious service attendance varies within our sample and have used semi-parametric models with ensemble learning and cross-validation to prevent data over-extrapolation and model over-fitting. Conceptually, it is crucial for valid causal inference that every potential level of \"treatment\" to religious services is realistically possible (refer to discussion in @vanderweele2017causaleffectsService). Although there are instances realised in our data of secular individuals initiating religious service and frequent attendees stopping (refer to @tbl-transition), it might stretch credulity too far to imagine that such changes are possible for everyone.\n\n\nSecond, our study confronts the spectre of **measurement error**: both direct and correlated measurement errors can introduce biases, either by implying effects where none exist or by attenuating true effects [@vanderweele2012MEASUREMENT]. Importantly, evaluating prosociality using multiple measures while also controlling for these measures and the treatment at baseline helps to mitigate measurement error concerns. Nevertheless, unknown combinations of measurement error might nevertheless bias our results. The outcomes and estimates we report here are best-considered approximations.\n\nThird, we do not examine **treatment effect heterogeneity**: identifying which subgroups experience the strongest responses remains a task for future research. Such investigations are crucial for making informed policy decisions and tailoring advice relevant to those subgroups of the population who might benefit most. Perhaps the most obvious stratum is religious affiliates [@vanderweele2017causaleffectsService].\n\nFourth, the **transportability of our findings remains unclear**: New Zealand is our target population. Our findings generalise to this population. However, the transportability of our findings to other settings—whether our results generalise beyond our targeted New Zealand population—remains an open question, a matter for future investigations. \n\n### Observations and Recommendations\n\nFirst, it is essential to notice that \"Does religion cause prosociality?\" lacks specificity. To refine this question, we must articulate clear causal contrasts and their scale, select specific measures of \"prosociality,\" define our target population, gather appropriate time-series data, and, only after causal assumptions and identification criteria are satisfied and threats made explicit, calculate statistical estimates. Having obtained these estimates, which rely on assumptions, we must evaluate robustness using sensitivity analyses [@hernan2024WHATIF; @ogburn2021; @bulbulia2022; @linden2020EVALUE; @vanderweele2020].  \n\nHere, we obtain statistical estimates for the causal effects of religious service on charity and volunteering by (1) stating contrasts for specific interventions that increase and decrease religious service attendance across the population; (2) balancing the interventions to be compared on baseline confounders measured one year before treatment (including baseline measures of the treatment and outcomes) using flexible doubly robust machine learning ensembles with cross-validation; and (3) evaluating contrasts in expected average outcomes under different treatments one year after treatment. \n\nIn the scientifically interesting contrast condition, ‘Regular vs Zero’, we find considerable social benefits of regular religious attendance for charitable donations and volunteering. Moreover, we also find that regular religious service enacted in contemporary New Zealand would strongly enhance charity and volunteering above the status quo, a point that may inform discussions among critics of religion. Conversely, the overall social effects of altogether ceasing religious services are minimal compared with the status quo. Were New Zealand society to entirely forgo regular religious attendance, differences in charitable donations and volunteering one year later are unreliable. Although we did not investigate the long-term effects of the interventions considered here, this finding should alleviate some concerns among those wary of New Zealand's longstanding secular trend. Looking ahead, **we recommend that future research distinguish between models of treatment-gain and models of treatment-loss** (as exemplified by @vantongeren2020).\n\nSecond, we caution that **classical measures of effect, such as Cohen's *D* or $R^2$, may present a misleading indication of practical significance.**  Our study computed standardised differences in the continuous charity and volunteering outcomes. The contrast between regular religious service and no service yields and effects size of 0.132 [0.102, 0.161]. This effect would be categorised as “small” effect by contemporary experimental conventions. Nonetheless, we project that the difference in annual charitable donations between the regular service condition and the status quo amounts to NZD 1638.98 versus NZD 1037.14. Not only is this effect practically significant at the individual level, summed over the population the difference amounts to 4% of New Zealand's Annual Government Budget (2021). **We recommend using causal inference to prioritise, evaluate and communicate practical effect sizes. Conventional statistical measures should not be mistaken for metrics of practical significance.**   \n\nThird, our novel measures of prosociality—**assistance and financial support received from one's community**--align with the expectations of self-reported data on charitable donations and volunteering. We detect marginal causal effects of religious service attendance on **measures of prosocial benefit and dependence**. Notice that just as our measures of prosocial actions (charity/volunteering) do not capture the targets of prosocial help, likewise our measures of community help received (time/money) do not capture the specific sources of help beyond the categories of \"community,\" \"friends,\" and \"family\". Nevertheless, the evolutionary theories of religious prosociality that motivate this study are grounded on within-group cooperative benefits [@sosis2003cooperation; @johnson2015; @bulbulia2012spreading;  @whitehouse2023; @schloss2011evolutionary]. This consistency between self-reported giving and help received aligns with public data in New Zealand;[^charities] where religious institutional charity accounts for 40% of the charitable sector (refer to @McLeod2020, p.17, and also @brooks2004faith; @woodyard2014doing; @monsma2007religion). Additionally, religious institutions appear particularly efficient owing to low administrative costs and high volunteer engagement [@khanna1995charity; @bekkers2011literature; @McLeod2020, p.26]. We note that the community signals of religious giving are consistent with the theory that religion promotes altruism outside families, friendships, and even among strangers [@mccullough2020kindness]. **In contexts where investigators are concerned about self-presentation biases when surveying charitable donations and volunteering, we recommend piloting and deploying measures that capture community-received assistance.**\n\n[^charities]: [https://www.charities.govt.nz/view-data/](https://www.charities.govt.nz/view-data/)\n\nFourth, our secondary analysis reveals that standard cross-sectional regressions overstate the causal effects estimates obtained from a conscientious application of causal methods to time-series data. Importantly, associational models might also *understate* true causal relationships, especially if adjustments involve mediators [@westreich2013; @mcelreath2020]. Despite their effectiveness and relevance, causal inference methods remain uncommon in many human sciences, including the psychological sciences, where traditional associational methods still dominate. Transitioning to causal data science might seem daunting. Yet, causation inherently unfolds in time, with causes preceding effects. Estimating average causal effects involves multi-stepped workflows and robust time-series data [@neal2020introduction; @bulbulia2023]. Although the need for researchers to develop new skills imposes considerable demands, it is encouraging that methods for causal inference have become standard in epidemiology [@lash2020] and are rapidly gaining traction in economics [@angrist2009mostly; @athey2019; @athey2021] and political science [@montgomery2018]. \n\nMoreover, a global panel studies suited for researching religion @johnson2022global offers exciting opportunities for psychological scientists to apply causal methods to those psychological questions at the heart of our discipline. \n\nAlso encouraging, well-designed panel studies investigating the causal effects of religious service attendance on health that capitalise on the affordances of time-series data provide models for studies that may investigate the social consequences of religion (refer to @chen2020religious, @pawlikowski2019religious,@vanderweelechurchmortality,@vanderweele2021effectsReligiousServiceMetanalysis, @kim2019mediators). At present, then, the intellectual benefits of retooling would seem considerable (refer to @major2023exploring). \n\nSetting intellectual benefits aside, it is vital to remember that investigators should be able to evaluate the practical interest of their findings coherently. Such evaluation relies on quantifying the effects of interventions. However, associational methods cannot deliver this understanding where causal inferential workflows are absent because association is not guaranteed to be causation [@westreich2013]. What might be called a *practical significance gap* arises from associational models because we cannot interpret associations as causation unless we have obtained balance on the treatments to be compared, know that causes in our data precede effects in time, and ensure that identification conditions have been met. Notably, the *practical significance gap* remains for associational methods even when they are applied to time series data, and even when they are sophisticated—as in the statistical structural equation and multilevel modelling traditions (refer to @vanderweele2021can; @hazlett2022understanding). Yet, because investigators typically seek both scientific knowledge and practical understanding, **we strongly recommend the broader adoption of causal inferential methods in the psychological sciences.**\n\n\nFifth, and finally, we frame this study's contribution in light of future horizons. This study combined robust causal methods with national panel data to quantitatively investigate the social consequences of religious behaviour. Using both stated and revealed indicators, we provide evidence that religious service attendance causally affects charitable donations and volunteering. These findings offer insights into *how much* Religious service affects charity and volunteering in New Zealand and possibly in similar cultures. We hope this research will serve as a guide for studies in other settings. \n\nHowever, even within New Zealand, much remains to be discovered. We have not attempted to elucidate heterogeneity in the treatment effects we observe. Nor have we investigated the pathways by which religious service attendance affects social behaviours. A substantial body of research has examined the psychological and cultural features through which religious behaviours affect individuals [@norenzayan2016; @shaver2020church; @watts2016; @mccullough2016christian; @konvalinka2011synchronized; @lang2015effects; @cristofori2016neural; @shaver2015evolution; @sosis2005does]. Yet obtaining a causal understanding presents conceptual, modelling, and data challenges [@robins1992; @vanderweele2015; @Diaz2023; @diaz2021nonparametric]. In the years ahead, **we recommend the wider development and application of causal inferential methods employing repeated measurements over more than three years to investigate variation, interaction, and causal mediation**. \n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n### Ethics\n\nThe University of Auckland Human Participants Ethics Committee reviews the NZAVS every three years. Our most recent ethics approval statement is as follows: The New Zealand Attitudes and Values Study was approved by the University of Auckland Human Participants Ethics Committee on 26/05/2021 for six years until 26/05/2027, Reference Number UAHPEC22576.\n\n\n### Data Availability\n\nThe data described in the paper are part of the New Zealand Attitudes and Values Study (NZAVMembers of the NZAVS management team and research group hold full copies of the NZAVS data. A de-identified dataset containing only the variables analysed in this manuscript is available upon request from the corresponding author or any member of the NZAVS advisory board for replication or checking of any published study using NZAVS data. The code for the analysis can be found at: [https://github.com/go-bayes/models/blob/main/scripts/24-bulbulia-church-prosocial.R](https://github.com/go-bayes/models/blob/main/scripts/24-bulbulia-church-prosocial.R). \n\n\n<!-- ### Acknowledgements -->\n\n<!-- The New Zealand Attitudes and Values Study is supported by a grant from the Templeton Religious Trust (TRT0196; TRT0418). JB received support from the Max Planck Institute for the Science of Human History. The funders had no role in preparing the manuscript or deciding to publish it. -->\n\n\n<!-- ### Author Statement -->\n\n<!-- JB conceived the study and approach. CS led NZAVS data collection. All authors contributed to the manuscript. -->\n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n## Appendix A: Measures {#appendix-measures}\n\n#### Age (waves: 1-15)\n\nWe asked participants' ages in an open-ended question (\"What is your age?\" or \"What is your date of birth?\").\n\n\n#### Born in New Zealand\n\n\n#### Charitable Donations  (Study 1 outcome)\n\nUsing one item from @hoverd_religious_2010, we asked participants, \"How much money have you donated to charity in the last year?\". \n\n<!-- To stabilise this indicator, we took the natural log of the response + 1. -->\n\n\n#### Charitable Volunteering  (Study 1 outcome)\n\n\nWe measured hours of volunteering using one item from @sibley2011: \"Hours spent … voluntary/charitable work.\"\n\n<!-- To stabilise this indicator, we took the natural log of the response + 1. -->\n\n#### Children Number (waves: 1-3, 4-15)\n\nWe measured the number of children using one item from @Bulbulia_2015. We asked participants, \"How many children have you given birth to, fathered, or adopted. How many children have you given birth to, fathered, or adopted?\" or \"How many children have you given birth to, fathered, or adopted. How many children have you given birth to, fathered, and/or parented?\" (waves: 12-15).\n\n<!-- Here, we used responses to create a binary indicator for parenthood: Parent Yes = 1/ No = 0.  -->\n\n\n\n<!-- #### Community: Sense of Community (Study 2 outcome) -->\n\n<!-- We measured a sense of community with a single item from @sengupta2013: \"I feel a sense of community with others in my local neighbourhood.\" Participants answered on a scale of 1 (strongly disagree) to 7 (strongly agree). -->\n\n\n<!-- #### Community: Felt Belongingness  (Study 2 outcome) -->\n\n<!-- We assessed felt belongingness with three items adapted from the Sense of Belonging Instrument [@hagerty1995]: (1) \"Know that people in my life accept and value me\"; (2) \"Feel like an outsider\"; (3) \"Know that people around me share my attitudes and beliefs\". Participants responded on a scale from 1 (Very Inaccurate) to 7 (Very Accurate). The second item was reversely coded. -->\n\n<!-- #### Community: Social Support (Study 2 outcome) -->\n\n<!-- Participants perceived social support was measured using three items from @cutrona1987 and @williams_cyberostracism_2000: (1) \"There are people I can depend on to help me if I really need it\"; (2) \"There is no one I can turn to for guidance in times of stress\"; (3) \"I know there are people I can turn to when I need help.\" Participants indicated how much they agreed with those items (1 = Strongly Disagree to 7 = Strongly Agree). The second item was negatively worded, so we reversely recorded the responses to this item. -->\n\n#### Disability\n\nWe assessed disability with a one-item indicator adapted from @verbrugge1997. It asks, \"Do you have a health condition or disability that limits you and that has lasted for 6+ months?\" (1 = Yes, 0 = No).\n\n\n#### Education Attainment (waves: 1, 4-15)\n\nWe asked participants, \"What is your highest level of qualification?\". We coded participants' highest finished degree according to the New Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with overseas school quals coded as Level 3, and all other ancillary categories coded as missing) See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf\n\n#### Employment (waves: 1-3, 4-11)\n\nWe asked participants, \"Are you currently employed? (This includes self-employed or casual work)\".\n\n<!-- #### European (waves: 1-15) -->\n\n<!-- Participants were asked, \"Which ethnic group do you belong to (NZ census question)?\" or \"Which ethnic group(s) do you belong to? (Open-ended)\" (wave: 3). Europeans were coded as 1, whereas other ethnicities were coded as 0. -->\n\n#### Ethnicity\n\nBased on the New Zealand Census, we asked participants, \"Which ethnic group(s) do you belong to?\". The responses were: (1) New Zealand European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6) Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE, TOKELAUAN. Please state:. We coded their answers into four groups: Maori, Pacific, Asian, and Euro (except for Time 3, which used an open-ended measure).\n\n\n#### Fatigue\n\nWe assessed subjective fatigue by asking participants, \"During the last 30 days, how often did ... you feel exhausted?\" Responses were collected on an ordinal scale (0 = None of The Time, 1 = A little of The Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time).\n\n\n#### Honesty-Humility-Modesty Facet (waves: 10-14)\n\nParticipants indicated the extent to which they agree with the following four statements from @campbell2004 , and @sibley2011 (1 = Strongly Disagree to 7 = Strongly Agree)\n\n```\ni.  I want people to know that I am an important person of high status, (Waves: 1, 10-14)\nii. I am an ordinary person who is no better than others.\niii. I wouldn't want people to treat me as though I were superior to them.\niv. I think that I am entitled to more respect than the average person is.\n```\n\n<!-- #### Has Siblings -->\n\n<!-- \"Do you have siblings?\" [@stronge2019onlychild] -->\n\n#### Hours of Childcare\n\nWe measured hours of exercising using one item from @sibley2011: 'Hours spent … looking after children.\"\n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n\n#### Hours of Housework\n\nWe measured hours of exercising using one item from @sibley2011: \"Hours spent … housework/cooking\"\n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n#### Hours of Exercise\n\nWe measured hours of exercising using one item from @sibley2011: \"Hours spent … exercising/physical activity\" \n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n<!-- #### Hours Volunteering -->\n\n<!-- We measured hours of volunteering using one item from @sibley2011: \"Hours spent … voluntary/charitable work.\" -->\n\n<!-- To stabilise this indicator, we took the natural log of the response + 1. -->\n\n#### Hours of Childcare\n\nWe measured hours of exercising using one item from @sibley2011: 'Hours spent … looking after children.\"\n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n\n#### Hours of Exercise\n\nWe measured hours of exercising using one item from @sibley2011: \"Hours spent … exercising/physical activity\" \n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n\n#### Hours of Housework\n\nWe measured hours of exercising using one item from @sibley2011: \"Hours spent … housework/cooking\"\n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n\n#### Hours of Sleep\n\nParticipants were asked, \"During the past month, on average, how many hours of *actual sleep* did you get per night?\".\n\n\n#### Hours of Work\n\nWe measured work hours using one item from @sibley2011: \"Hours spent … working in paid employment.\"\n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n\n#### Income (waves: 1-3, 4-15)\n\nParticipants were asked, \"Please estimate your total household income (before tax) for the year XXXX\". To stabilise this indicator, we first took the natural log of the response + 1, and then centred and standardised the log-transformed indicator.\n\n<!-- #### Job Security (waves: 1-3,4-7,9-15) -->\n\n<!-- Participants indicated their feeling of job security by answering \"How secure do you feel in your current job?\" on a scale from 1 (not secure) to 7 (very secure). -->\n\n\n#### Kessler-6: Psychological Distress  (waves: 2-3,4-15)\n\nWe measured psychological distress using the Kessler-6 scale (kessler2002?), which exhibits\nstrong diagnostic concordance for moderate and severe psychological distress in large, crosscultural\nsamples (kessler2010?; prochaska2012?). Participants rated during the past 30\ndays, how often did… (1) “… you feel hopeless”; (2) “… you feel so depressed that nothing\ncould cheer you up”; (3) “… you feel restless or fidgety”; (4)“… you feel that everything was\nan effort”; (5) “… you feel worthless”; (6) ” you feel nervous?” Ordinal response alternatives\nfor the Kessler-6 are: “None of the time”; “A little of the time”; “Some of the time”; “Most of\nthe time”; “All of the time.”\n\n\n#### Male Gender (waves: 1-15)\n\nWe asked participants' gender in an open-ended question: \"what is your gender?\" or \"Are you male or female?\" (waves: 1-5). Female was coded as 0, Male as 1, and gender diverse coded as 3 [@fraser_coding_2020]. (or 0.5 = neither female nor male)\n\nHere, we coded all those who responded as Male as 1, and those who did not as 0.\n\n\n#### Mini-IPIP 6 (waves: 1-3,4-15)\n\nWe measured participants' personalities with the Mini International Personality Item Pool 6 (Mini-IPIP6) [@sibley2011], which consists of six dimensions and each dimension is measured with four items:\n\n1.  agreeableness,\n\n    i.  I sympathize with others' feelings.\n    ii. I am not interested in other people's problems. (r)\n    iii. I feel others' emotions.\n    iv. I am not really interested in others. (r)\n\n2.  conscientiousness,\n\n    i.  I get chores done right away.\n    ii. I like order.\n    iii. I make a mess of things. (r)\n    iv. I often forget to put things back in their proper place. (r)\n\n3.  extraversion,\n\n    i.  I am the life of the party.\n    ii. I don't talk a lot. (r)\n    iii. I keep in the background. (r)\n    iv. I talk to a lot of different people at parties.\n\n4.  honesty-humility,\n\n    i.  I feel entitled to more of everything. (r)\n    ii. I deserve more things in life. (r)\n    iii. I would like to be seen driving around in a very expensive car. (r)\n    iv. I would get a lot of pleasure from owning expensive luxury goods. (r)\n\n5.  neuroticism, and\n\n    i.  I have frequent mood swings.\n    ii. I am relaxed most of the time. (r)\n    iii. I get upset easily.\n    iv. I seldom feel blue. (r)\n\n6.  openness to experience\n\n    i.  I have a vivid imagination.\n    ii. I have difficulty understanding abstract ideas. (r)\n    iii. I do not have a good imagination. (r)\n    iv. I am not interested in abstract ideas. (r)\n\nEach dimension was assessed with four items and participants rated the accuracy of each item as it applies to them from 1 (Very Inaccurate) to 7 (Very Accurate). Items marked with (r) are reverse coded.\n\n\n#### NZ-Born (waves: 1-2,4-15)\n\nWe asked participants, \"Which country were you born in?\" or \"Where were you born? (please be specific, e.g., which town/city?)\" (waves: 6-15).\n\n\n#### NZ Deprivation Index (waves: 1-15)\n\nWe used the NZ Deprivation Index to assign each participant a score based on where they live [@atkinson2019]. This score combines data such as income, home ownership, employment, qualifications, family structure, housing, and access to transport and communication for an area into one deprivation score.\n\n\n#### NZSEI Occupational Prestige and Status (waves: 8-15)\n\nWe assessed occupational prestige and status using the New Zealand Socio-economic Index 13 (NZSEI-13) [@fahy2017a]. This index uses the income, age, and education of a reference group, in this case the 2013 New Zealand census, to calculate a score for each occupational group. Scores range from 10 (Lowest) to 90 (Highest). This list of index scores for occupational groups was used to assign each participant an NZSEI-13 score based on their occupation.\n\nWe assessed occupational prestige and status using the New Zealand Socio-economic Index 13 (NZSEI-13) [@fahy2017]. This index uses the income, age, and education of a reference group, in this case, the 2013 New Zealand census, to calculate a score for each occupational group. Scores range from 10 (Lowest) to 90 (Highest). This list of index scores for occupational groups was used to assign each participant an NZSEI-13 score based on their occupation.\n\n<!-- We asked participants, \"If you are a parent, what is the birth date of your eldest child?\". -->\n<!-- #### Parent (waves: 5-15) -->\n\n<!-- We asked participants, \"If you are a parent, what is the birth date of your eldest child?\" or \"If you are a parent, in which year was your eldest child born?\" (waves: 10-15). Parents were coded as 1, while the others were coded as 0. --> \n\n\n\n\n#### Opt-in\n\nThe New Zealand Attitudes and Values Study allows opt-ins to the study. Because the opt-in population may differ from those sampled randomly from the New Zealand electoral roll; although the opt-in rate is low, we include an indicator (yes/no) for this variable.\n\n\n\n#### Partner (No/Yes)\n\n\"What is your relationship status?\" (e.g., single, married, de-facto, civil union, widowed, living together, etc.)\n\n\n#### Politically Conservative \n\nWe measured participants' political conservative orientation using a single item adapted from @jost_end_2006-1.\n\n\"Please rate how politically liberal versus conservative you see yourself as being.\"\n\n(1 = Extremely Liberal to 7 = Extremely Conservative)\n\n\n##### Religious Service Attendance\n\nIf participants answered *yes* to \"Do you identify with a religion and/or spiritual group?\" we measured their frequency of church attendence using one item from @sibley2012: \"how many times did you attend a church or place of worship in the last month?\". Those participants who were not religious were imputed a score of \"0\".\n\n#### Rural/Urban Codes\n\nParticipants residence locations were coded according to a five-level ordinal categorisation ranging from \"Urban\" to Rural, see @sibley2021.\n\n<!-- #### Politically Right Wing  -->\n\n<!-- We measured participants' political right-wing orientation using a single item adapted from @jost_end_2006-1. -->\n\n<!-- \"Please rate how politically left-wing versus right-wing you see yourself as being.\" -->\n\n<!-- (1 = Extremely left-wing to 7 = Extremely right-wing) -->\n\n\n<!-- #### Religion Affiliation -->\n\n<!-- Participants were asked to indicate their religion identification (\"Do you identify with a religion and/or spiritual group?\") on a binary response (1 = Yes, 0 = No). We then asked, \"What religion or spiritual group?\" These questions are used in the New Zealand Census -->\n\n\n<!-- #### Support -->\n\n<!-- Participants' perceived social support was measured using three items from @cutrona1987 and @williams_cyberostracism_2000: (1) \"There are people I can depend on to help me if I really need it\"; (2) \"There is no one I can turn to for guidance in times of stress\"; (3) \"I know there are people I can turn to when I need help.\" Participants indicated how much they agreed with those items (1 = Strongly Disagree to 7 = Strongly Agree). The second item was negatively worded, so we reversely recorded the responses to this item. -->\n\n#### Short-Form Health\n\nParticipants' subjective health was measured using one item (\"Do you have a health condition or disability that limits you, and that has lasted for 6+ months?\"; 1 = Yes, 0 = No) adapted from @verbrugge1997.\n\n\n#### Sample Origin\n\nWave enrolled in NZAVS, see @sibley2021.\n\n<!-- #### Socialising (time 10, time 11) -->\n\n<!-- As part of the time usage measures, participants were asked to state how many hour the spent in activities related to socialising with the following groups: -->\n\n<!--   - Hours spent … socialising with family -->\n<!--   - Hours spent … socialising with friends -->\n<!--   - Hours spent … socialising with community groups -->\n\n<!--   <!-- - Hours spent … socialising with religious groups -->\n\n\n#### Support received: money (waves 10-12) (Study 4 outcomes)\n\nThe NZAVS has a 'revealed' measure of received help and support measured in hours of support in the previous week. The items are: \n\n\n*Please estimate how much help you have received from the following sources in the last week?*\n\n- *family...MONEY (hours)*\n- *friends...MONEY (hours)*\n- *members of my community...MONEY (hours)*\n\n\nBecause this measure is highly variable, we convert responses to binary indicators: *0 = none/1 any*\n\n\n#### Support received: time (waves 10-13) (Study 3 outcomes)\n\n*Please estimate how much help you have received from the following sources in the last week.*\n\n- *family...TIME (hours)*\n- *friends...TIME (hours)*\n- *members of my community...TIME (hours)*\n\nBecause this measure is highly variable, we convert responses to binary indicators: *0 = none/1 any*\n  \n\n#### Total Siblings\n\nParticipants were asked the following questions related to sibling counts: \n \n - Were you the 1st born, 2nd born, or 3rd born, etc, child of your mother?\n - Do you have siblings?\n - How many older sisters do you have?\n - How many younger sisters do you have?\n - How many older brothers do you have?\n - How many younger brothers do you have?\n\nA single score was obtained from sibling counts by summing responses to the \"How many...\" items. From these scores, an ordered factor was created ranging from 0 to 7, where participants with more than 7 siblings were grouped into the highest category. \n\n\n<!-- #### Volunteers -->\n\n<!-- We asked participants,\"Please estimate how many hours you spent doing each of the following things last week\" and responded to an item (\"voluntary/charitable work\") from [@sibley2011]. -->\n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n## Appendix B. Baseline Demographic Statistics {#appendix-demographics}\n\n\n\n\n\n\n\n::: {#tbl-table-demography .cell tbl-cap='Baseline demographic statistics'}\n::: {.cell-output-display}\n\n\n|**Exposure + Demographic Variables** |**N = 33,198** |\n|:------------------------------------|:--------------|\n|__Age__                              |NA             |\n|Mean (SD)                            |51 (14)        |\n|Range                                |18, 96         |\n|IQR                                  |41, 61         |\n|__Agreeableness__                    |NA             |\n|Mean (SD)                            |5.37 (0.98)    |\n|Range                                |1.00, 7.00     |\n|IQR                                  |4.75, 6.00     |\n|Unknown                              |272            |\n|__Born Nz__                          |26,197 (79%)   |\n|Unknown                              |34             |\n|__Children Num__                     |NA             |\n|Mean (SD)                            |1.76 (1.44)    |\n|Range                                |0.00, 14.00    |\n|IQR                                  |0.00, 3.00     |\n|__Conscientiousness__                |NA             |\n|Mean (SD)                            |5.14 (1.04)    |\n|Range                                |1.00, 7.00     |\n|IQR                                  |4.50, 6.00     |\n|Unknown                              |266            |\n|__Education Level Coarsen__          |NA             |\n|no_qualification                     |769 (2.3%)     |\n|cert_1_to_4                          |11,278 (34%)   |\n|cert_5_to_6                          |4,281 (13%)    |\n|university                           |8,947 (27%)    |\n|post_grad                            |3,892 (12%)    |\n|masters                              |2,956 (9.0%)   |\n|doctorate                            |891 (2.7%)     |\n|Unknown                              |184            |\n|__Employed__                         |26,379 (80%)   |\n|Unknown                              |26             |\n|__Eth Cat__                          |NA             |\n|euro                                 |27,404 (83%)   |\n|maori                                |3,424 (10%)    |\n|pacific                              |707 (2.1%)     |\n|asian                                |1,438 (4.4%)   |\n|Unknown                              |225            |\n|__Extraversion__                     |NA             |\n|Mean (SD)                            |3.88 (1.20)    |\n|Range                                |1.00, 7.00     |\n|IQR                                  |3.00, 4.75     |\n|Unknown                              |266            |\n|__Hlth Disability__                  |7,558 (23%)    |\n|Unknown                              |561            |\n|__Hlth Fatigue__                     |NA             |\n|0                                    |5,289 (16%)    |\n|1                                    |10,940 (33%)   |\n|2                                    |10,196 (31%)   |\n|3                                    |4,862 (15%)    |\n|4                                    |1,577 (4.8%)   |\n|Unknown                              |334            |\n|__Hlth Sleep Hours__                 |NA             |\n|Mean (SD)                            |6.95 (1.11)    |\n|Range                                |2.50, 16.00    |\n|IQR                                  |6.00, 8.00     |\n|Unknown                              |1,528          |\n|__Honesty Humility__                 |NA             |\n|Mean (SD)                            |5.49 (1.15)    |\n|Range                                |1.00, 7.00     |\n|IQR                                  |4.75, 6.50     |\n|Unknown                              |269            |\n|__Hours Children log__               |NA             |\n|Mean (SD)                            |1.10 (1.58)    |\n|Range                                |0.00, 5.13     |\n|IQR                                  |0.00, 2.20     |\n|Unknown                              |875            |\n|__Hours Exercise log__               |NA             |\n|Mean (SD)                            |1.57 (0.83)    |\n|Range                                |0.00, 4.39     |\n|IQR                                  |1.10, 2.08     |\n|Unknown                              |875            |\n|__Hours Housework log__              |NA             |\n|Mean (SD)                            |2.15 (0.77)    |\n|Range                                |0.00, 5.13     |\n|IQR                                  |1.79, 2.71     |\n|Unknown                              |875            |\n|__Hours Work log__                   |NA             |\n|Mean (SD)                            |2.64 (1.59)    |\n|Range                                |0.00, 4.62     |\n|IQR                                  |1.10, 3.71     |\n|Unknown                              |875            |\n|__Household Inc log__                |NA             |\n|Mean (SD)                            |11.41 (0.76)   |\n|Range                                |0.69, 14.92    |\n|IQR                                  |11.00, 11.92   |\n|Unknown                              |1,352          |\n|__Kessler6 Sum__                     |NA             |\n|Mean (SD)                            |5 (4)          |\n|Range                                |0, 24          |\n|IQR                                  |2, 7           |\n|Unknown                              |297            |\n|__Male__                             |11,975 (36%)   |\n|__Modesty__                          |NA             |\n|Mean (SD)                            |6.03 (0.90)    |\n|Range                                |1.00, 7.00     |\n|IQR                                  |5.50, 6.75     |\n|Unknown                              |11             |\n|__Neuroticism__                      |NA             |\n|Mean (SD)                            |3.45 (1.15)    |\n|Range                                |1.00, 7.00     |\n|IQR                                  |2.50, 4.25     |\n|Unknown                              |274            |\n|__Nz Dep2018__                       |NA             |\n|Mean (SD)                            |4.69 (2.70)    |\n|Range                                |1.00, 10.00    |\n|IQR                                  |2.00, 7.00     |\n|Unknown                              |233            |\n|__Nzsei 13 l__                       |NA             |\n|Mean (SD)                            |55 (16)        |\n|Range                                |10, 90         |\n|IQR                                  |42, 69         |\n|Unknown                              |172            |\n|__Openness__                         |NA             |\n|Mean (SD)                            |4.99 (1.12)    |\n|Range                                |1.00, 7.00     |\n|IQR                                  |4.25, 5.75     |\n|Unknown                              |267            |\n|__Partner__                          |24,869 (76%)   |\n|Unknown                              |422            |\n|__Political Conservative__           |NA             |\n|1                                    |1,777 (5.6%)   |\n|2                                    |6,563 (21%)    |\n|3                                    |6,505 (20%)    |\n|4                                    |9,373 (29%)    |\n|5                                    |4,813 (15%)    |\n|6                                    |2,378 (7.5%)   |\n|7                                    |483 (1.5%)     |\n|Unknown                              |1,306          |\n|__Religion Church Round__            |NA             |\n|0                                    |27,653 (83%)   |\n|1                                    |1,077 (3.2%)   |\n|2                                    |777 (2.3%)     |\n|3                                    |658 (2.0%)     |\n|4                                    |1,729 (5.2%)   |\n|5                                    |336 (1.0%)     |\n|6                                    |226 (0.7%)     |\n|7                                    |74 (0.2%)      |\n|8                                    |668 (2.0%)     |\n|__Rural Gch 2018 l__                 |NA             |\n|1                                    |20,361 (62%)   |\n|2                                    |6,390 (19%)    |\n|3                                    |4,020 (12%)    |\n|4                                    |1,816 (5.5%)   |\n|5                                    |380 (1.2%)     |\n|Unknown                              |231            |\n|__Sample Frame Opt in__              |1,107 (3.3%)   |\n|__Sample Origin__                    |NA             |\n|1-2                                  |2,191 (6.6%)   |\n|3-3.5                                |1,664 (5.0%)   |\n|4                                    |1,987 (6.0%)   |\n|5-6-7                                |3,203 (9.6%)   |\n|8-9                                  |4,264 (13%)    |\n|10                                   |19,889 (60%)   |\n|__Short Form Health__                |NA             |\n|Mean (SD)                            |5.06 (1.16)    |\n|Range                                |1.00, 7.00     |\n|IQR                                  |4.33, 6.00     |\n|Unknown                              |5              |\n|__Total Siblings__                   |NA             |\n|Mean (SD)                            |2.52 (1.80)    |\n|Range                                |0.00, 23.00    |\n|IQR                                  |1.00, 3.00     |\n|Unknown                              |689            |\n\n\n:::\n:::\n\n\n\n\n\n\n\n@tbl-table-demography baseline demographic statistics for couples who met inclusion criteria.\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n##  Appendix C: Treatment Statistics {#appendix-exposures}\n\n\n\n\n\n\n\n::: {#tbl-table-exposures-code .cell tbl-cap='Exposures at baseline and baseline + 1 (treatment) wave'}\n::: {.cell-output-display}\n\n\n|**Exposure Variables by Wave** |**2018**, N = 33,198 |**2019**, N = 33,198 |\n|:------------------------------|:--------------------|:--------------------|\n|__Religion Church Round__      |NA                   |NA                   |\n|0                              |27,653 (83%)         |28,028 (84%)         |\n|1                              |1,077 (3.2%)         |896 (2.7%)           |\n|2                              |777 (2.3%)           |737 (2.2%)           |\n|3                              |658 (2.0%)           |639 (1.9%)           |\n|4                              |1,729 (5.2%)         |1,672 (5.0%)         |\n|5                              |336 (1.0%)           |308 (0.9%)           |\n|6                              |226 (0.7%)           |205 (0.6%)           |\n|7                              |74 (0.2%)            |68 (0.2%)            |\n|8                              |668 (2.0%)           |645 (1.9%)           |\n|Unknown                        |0                    |0                    |\n|__Alert Level Combined__       |NA                   |NA                   |\n|no_alert                       |33,198 (100%)        |23,751 (72%)         |\n|early_covid                    |0 (0%)               |3,643 (11%)          |\n|alert_level_1                  |0 (0%)               |2,821 (8.5%)         |\n|alert_level_2                  |0 (0%)               |836 (2.5%)           |\n|alert_level_2_5_3              |0 (0%)               |552 (1.7%)           |\n|alert_level_4                  |0 (0%)               |1,595 (4.8%)         |\n|Unknown                        |0                    |0                    |\n\n\n:::\n:::\n\n\n\n\n\n\n\n\ntbl-table-exposures-code presents baseline (NZAVS time 10) and exposure wave (NZAVS time 11) statistics for the exposure variable: religious service attendance (range 0-8). Responses coded as eight or above were coded as \"8\". This decision to avoid spare treatments was based on theoretical grounds, namely, that daily exposure would be similar in its effects to more than daily exposure. We note that causal contrasts were obtained for projects with either no attendance or four or more visits per month. Hence this simplification of the measure is unlikely to affect theoretical and practical inferences. All models adjusted for the pandemic alert level because the treatment wave (NZAVS time 11) occurred during New Zealand's COVID-19 pandemic. The pandemic is not a \"confounder\" because a confounder must be related to the treatment and the outcome. At the end of the study, all participants had been exposed to the pandemic.  However, to satisfy the causal consistency assumption, all treatments must be conditionally equivalent within levels of all covariates [@vanderweele2013]. Because COVID affected the ability or willingness of individuals to attend religious service, we included the lockdown condition as a covariate [@sibley2021]. To better enable conditional independence within levels of the treatment variable, we conditioned on the lead value of COVID-alert level at baseline. To mitigate systematic biases arising from attrition and missingness, the `lmtp` package uses inverse probability of censoring weights, which were used when estimating the causal effects of the exposure on the outcome. \n\n\n\n### Binary Transition Table for The Treatment\n\n\n\n\n\n\n::: {#tbl-transition-tablegain .cell tbl-cap='Transition table for stability and change in regular religious service (4x per month) between baseline and treatment wave.'}\n::: {.cell-output-display}\n\n\n| From |    >=4    |   < 4    |\n|:----:|:---------:|:--------:|\n| >=4  | **29496** |   669    |\n| < 4  |    804    | **2229** |\n\n\n:::\n:::\n\n\n\n\n\n\n@tbl-transition-tablegain presents a transition matrix to evaluate treatment shifts between baseline and treatment wave. Here, we focus on the shift from/to monthly attendance at four or more visits per month. Entries along the diagonal (in bold) indicate the number of individuals who **stayed** in their initial state. By contrast, the off-diagonal shows the transitions from the initial state (bold) to another state in the following wave (off diagonal). Thus the cell located at the intersection of row $i$ and column $j$, where $i \\neq j$, gives us the counts of individuals moving from state $i$ to state $j$.\n\n\n\n\n\n\n\n\n\n\n::: {#tbl-transition-tableloss .cell tbl-cap='Transition table for stability and change in zero religious service (0 x per month) between baseline and treatment wave.'}\n::: {.cell-output-display}\n\n\n| From |     0     |   > 0    |\n|:----:|:---------:|:--------:|\n|  0   | **26762** |   891    |\n| > 0  |   1266    | **4279** |\n\n\n:::\n:::\n\n\n\n\n\n\n@tbl-transition-tableloss presents a transition matrix to evaluate treatment shifts between baseline and treatment wave. Here, we focus on the shift from/to zero religious service attendance. Again, entries along the diagonal (in bold) indicate the number of individuals who **stayed** in their initial state. By contrast, the off-diagonal shows the transitions from the initial state (bold) to another state in the following wave (off diagonal). Thus the cell located at the intersection of row $i$ and column $j$, where $i \\neq j$, gives us the counts of individuals moving from state $i$ to state $j$.\n\n\n### Imbalance of Confounding Covariates Treatments \n\n@fig-match_1 shows imbalance of covariates on the treatment at the treatment wave. The variable on which there is strongest imbalance is the baseline measure of religious service attendance. It is important to adjust for this measure both for confounding control and to better estimate an incident exposure effect for the religious service at the treatment wave (in contrast to merely estimating a prevalence effect). See @vanderweele2020.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![This figure shows the imbalance in covariates on the treatment](psyc_434_manuscript_template_files/figure-html/fig-match_1-1.png){#fig-match_1 width=960}\n:::\n:::\n\n\n\n\n\n\n\n##  Appendix D: Baseline and End of Study Outcome Statistics {#appendix-outcomes}\n\n\n\n\n\n\n\n::: {#tbl-table-outcomes .cell tbl-cap='Outcomes at baseline and end-of-study'}\n::: {.cell-output-display}\n\n\n|**Outcome Variables by Wave**     |**2018**, N = 33,198 |**2020**, N = 33,198 |\n|:---------------------------------|:--------------------|:--------------------|\n|__Annual Charity__                |150 (40, 500)        |200 (20, 600)        |\n|Unknown                           |1,076                |6,730                |\n|__Community Gives Money Binary__  |135 (0.4%)           |118 (0.4%)           |\n|Unknown                           |669                  |6,959                |\n|__Community Gives Time Binary__   |1,702 (5.2%)         |1,669 (6.4%)         |\n|Unknown                           |669                  |6,959                |\n|__Family Gives Money Binary__     |1,782 (5.5%)         |1,236 (4.7%)         |\n|Unknown                           |669                  |6,959                |\n|__Family Gives Time Binary__      |9,539 (29%)          |7,600 (29%)          |\n|Unknown                           |669                  |6,959                |\n|__Friends Give Money Binary__     |372 (1.1%)           |270 (1.0%)           |\n|Unknown                           |669                  |6,959                |\n|__Friends Give Time__             |5,765 (18%)          |4,855 (19%)          |\n|Unknown                           |669                  |6,959                |\n|__Sense Neighbourhood Community__ |NA                   |NA                   |\n|1                                 |1,976 (6.0%)         |1,124 (4.2%)         |\n|2                                 |4,037 (12%)          |2,703 (10%)          |\n|3                                 |4,796 (15%)          |3,561 (13%)          |\n|4                                 |6,840 (21%)          |5,809 (22%)          |\n|5                                 |7,088 (21%)          |6,477 (24%)          |\n|6                                 |5,753 (17%)          |5,060 (19%)          |\n|7                                 |2,550 (7.7%)         |2,104 (7.8%)         |\n|Unknown                           |158                  |6,360                |\n|__Social Belonging__              |5.33 (4.33, 6.00)    |5.33 (4.33, 6.00)    |\n|Unknown                           |268                  |6,418                |\n|__Social Support__                |6.33 (5.33, 7.00)    |6.33 (5.33, 7.00)    |\n|Unknown                           |19                   |6,286                |\n|__Volunteering Hours__            |0.00 (0.00, 1.00)    |0.00 (0.00, 1.00)    |\n|Unknown                           |875                  |6,863                |\n|__Volunteers Binary__             |9,443 (29%)          |6,881 (26%)          |\n|Unknown                           |875                  |6,863                |\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n@tbl-table-outcomes presents baseline and end-of-study descriptive statistics for the outcome variables.  \n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n\n## References {.appendix}\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "psyc_434_manuscript_template_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}