{
  "hash": "6d6ba730732355cd8f144554303c3e06",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Your Title Here\"\nabstract: |\n   Your abstract herr. \n   \n   **KEYWORDS**: *Causal Inference*; *Cross-validation*; *Longitudinal*; *Machine Learning*;  *Semi-parametric*; *Targeted Learning*; *TMLE*; **OTHERS**; **FEWER**.\nauthor: \n  - name: YOUR NAME HERE\n    affiliation: Victoria University of Wellington, New Zealand\n    orcid: 0000-0000-0000-0000\n    email: your.name@vuw.ac.nz\n    corresponding: yes\n  - name: YOUR CO-AUTHOR HERE\n    affiliation: Georgia State University, Matheny Center for the Study of Stress, Trauma, and Resilience\n    orcid: 0000-0000-0000-0000\n    email: your.coauthor@gsu.edu\neditor_options: \n  chunk_output_type: console\nformat:\n  docx: \n    bibliography: /Users/joseph/GIT/templates/bib/references.bib\n  pdf:\n    sanitise: true\n    keep-tex: true\n    link-citations: true\n    colorlinks: true\n    documentclass: article\n    classoption: [single column]\n    lof: false\n    lot: false\n    geometry:\n      - top=30mm\n      - left=25mm\n      - heightrounded\n      - headsep=22pt\n      - headheight=11pt\n      - footskip=33pt\n      - ignorehead\n      - ignorefoot\n    header-includes:\n      - \\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}\n    template-partials: \n      - /Users/joseph/GIT/templates/quarto/title.tex\ndate: last-modified\nexecute:\n  echo: false\n  warning: false\n  include: true\n  eval: true\nfontfamily: libertinus\nbibliography: /Users/joseph/GIT/templates/bib/references.bib\ncsl: /Users/joseph/GIT/templates/csl/camb-a.csl\n---\n\n\n\n\n\n\n\n\n\n\n## Introduction\n\nA central question in the scientific study of XXXX is whether YYYY fosters ZZZZZ [@johnson2005; @norenzayan2016; @watts2016; @watts2015; @sosis2003cooperation; @whitehouse2023; @schloss2011evolutionary; @swanson1967; @decoulanges1903; @wheatley1971]. However, quantifying causal effects for YYYY, and many other social behaviours presents significant challenges. \n\nInvestigators have limited scope to randomise YYYY on ZZZZZ. On the other hand, valid causal inferences from non-experimental or observational data must combine high-resolution repeated-measures time-series data with robust methods for causal inference. Few studies meet this standard... \n\nAn encouraging recent attempt to obtain valid causal inference is PPPP's thoughtful investigation of the relationships between religious attendance, beliefs, and affiliation on blood donations among pregnant women and their partners who were residents of Bristol, United Kingdom, in the early 1990s and participated in the Avon Longitudinal Study of Parents and Children, $N=13,477$ mothers and $N=13,424$ partners [@major2023exploring]. PPPP's study begins with a careful overview of the threats to causal inference from confounding and selection bias....\n\nAlthough we may sometimes use cross-sectional associations to obtain credible suggestions about causality, we cannot typically attach causal interpretations, at least not without strong assumptions about the relative order and timing of events [@vanderweele2021can]. Indeed, below we report an analysis restricted to baseline New Zealand Attitudes and Values Study data that observes a 2.65 times overstatement for the effect of perfectionism on anxiety and a 2.43 times overstatement for perfectionism's effect on depression...\n\n\nHere, to obtain causal inferences from time-series data, we leverage comprehensive panel data from a **SYNTHETIC DATASET** for 19,997 participants in the New Zealand Attitudes and Values Study from 2018-2021 to quantify the effects of clearly defined interventions in religious attendance across the population of New Zealanders on two features of mental health: \"Depression\" and \"Anxiety\" These outcomes are called “counterfactual” or “potential” outcomes, terms we use interchangeably [@rubin2005; @neyman1923; @robins1986; @pearl2009; @vanderlaan2018].[^theory] \n\nA fundamental challenge in observational studies is to ensure *balance* between the variables in interventions or “treatments” to be compared that might affect both treatment and the potential outcomes under treatment [@shiba2021using]. We call the state of imbalance *confounding*, and the strategy for ensuring balance, *confounding control.* In this study, we express the interventions on religious service as \"modified treatment policies\" [@haneuse2013estimation; @diaz2023lmtp; @díaz2021; @hoffman2023]. We obtain causal inferences by contrasting inferred population averages under different modified treatment policies.\n\n[^theory]: Philosophical disagreements about the meanings assigned to \"potential\" and \"counterfactual\" outcomes do not affect our use.\n\nOur initial causal contrast investigates: \"What would be the average difference across the New Zealand population if everyone were to become one unit greater on a 1-7 ordinal scale in Perfectionism versus the status quo\" This contrast addresses the practically interesting question ... \n\nA second analysis investigates whether there are differences in the causal effects of perfectionism among those born in New Zealand and those born oveseas.  A considerable body of acculturation research suggestions...  yadda yadda\n\nNote that our approach does not focus on testing specific hypotheses; instead, we aim to compute our pre-specified causal contrasts with high accuracy by combining appropriate time-series data and robust methods for causal inference [@hernan2024stating].\n\n\n## Method\n\n### Sample\n\nData were *SIMULATED* from responses to the New Zealand Attitudes and Values Study (NZAVS), an annual longitudinal national probability panel study of social attitudes, personality, ideology, and health outcomes in New Zealand. Chris G. Sibley started the New Zealand Attitudes and Values Study in 2009, which has grown to include a community of over fifty researchers. In this simulated dataset there were 20,000 New Zealand residents. The New Zealand Attitudes and Values Study operates independently of political or corporate funding and is based in a university setting. Data summaries for our study sample on all measures used in this study are found in **Appendices B-D**.  For more details about the New Zealand Attitudes and Values Study see: [OSF.IO/75SNB](https://doi.org/10.17605/OSF.IO/75SNB).\n\n### Treatment Indicator\n\nPerfectionism was assessed using a three item \"almost perfect scale\":\n\n- *Yadda*\n- *Yadda*\n- *Dadda*\n\n\n### Measures of Well-Being\n\n\nKessler-6. Yadda... \n\n- Anxiety:\n  *\"Yadda*\n  \n- Depression:\n  *Yadda*\n\n\n**Subgroup Analysis** \n\nWe assessed group differences in these effects ....\n\n\nWe provide comprehensive details of all measures in **Appendix A**.\n\n\n### Causal Interventions\n\nWe define three targeted causal contrasts (*causal estimands*) as interventions on prespecified modified treatment policies (refer to @haneuse2013estimation; @diaz2021nonparametric; @diaz2023lmtp). Let $A_t$ denote the treatment -- monthly frequency of religious service. There are three time points: $t\\in{0,1,2}$, where $t=0$ denotes the baseline wave, $t=1$, the treatment wave, and $t=2$ at the end of the study. $\\mathbf{d}(\\cdot)$ denotes a modified treatment policy $f_\\mathbf{d}$. When a treatment is fixed to a level defined by the modified treatment policy, perhaps contrary to a participant's observed level of treatment, we use the lowercase symbol $a_1$. Here, the functions defined by modified treatment policies $f_\\mathbf{d}$ are interventions that fix $A_1$ to $a_1$.\n\n1. **Regular Religious Service Treatment**: Administer treatment that leads to a +1 unit greater perfectionism to everyone in the adult population from 1-7 on the perfectionism scale. If an individual's perfectionism is within one unit of the top of the range, adminster the maximum value at the range:\n\n$$\n\\mathbf{d}^\\lambda (a_1) = \\begin{cases} 7 & \\text{if } a_1 <  6 \\\\ \na_1 + 1 & \\text{otherwise} \\end{cases}\n$$\n\n<!-- 2. **Zero Religious Service Treatment**: Ensure no religious service attendance for everyone in the adult population of New Zealand. If an individual's religious service attendance is greater than zero, shift to zero; otherwise, make no change: -->\n\n<!-- $$ -->\n<!-- \\mathbf{d}^\\phi (a_1) = \\begin{cases} 0 & \\text{if } a_1 > 0 \\\\  -->\n<!-- a_1 & \\text{otherwise} \\end{cases} -->\n<!-- $$ -->\n\n3. **Status Quo -- No Treatment**: Apply no treatment. Each expected mean outcome is calculated using each individual's natural (observed) value of religious service attendance.\n\n\n$$\n\\mathbf{d}(a_1) = a_1\n$$\n\n\n### Causal Contrasts\n\nFrom these policies, we compute the following causal contrasts.\n\n\n**Target Contrast B: 'Regular vs. Status Quo'**: What is the marginal effect of the treatment in New Zealand compared with its status quo?\n\n$$ \\text{Regular Religious Service vs. No Treatment} = E[Y(\\mathbf{d}^\\lambda) - Y(\\mathbf{d})] $$\n\nThis contrast reflects a policy-relevant hypothetical experiment examining the effect of shifting everyone's perfectionism up by one point, allowing us to quantitatively assess how much a society in which everyone attends would differ from a society in its current state. \n\n<!-- **Target Contrast C: 'Zero vs. Status Quo'**: What are the social consequences for society of zero religious service attendance compared to its status quo? -->\n\n<!-- $$ \\text{Zero Religious Service vs. No Treatment} = E[Y(\\mathbf{d}^\\phi) - Y(\\mathbf{d})] $$ -->\n\n<!-- This contrast investigates the policy implications of eliminating religious services entirely, questioning whether such a shift would meaningfully affect average levels of charitable donations and volunteering. -->\n\n### Identification Assumptions\n\nTo consistently estimate a causal effect, investigators must satisfy three assumptions:\n\n1. **Causal consistency:** potential outcomes must correspond with observed outcomes under the treatments in the data. Essentially, we assume potential outcomes do not depend on how the treatment was administered, conditional on measured covariates [@vanderweele2009; @vanderweele2013]. \n\n2. **Exchangeability**: given observed covariates, we assume treatment assignment is independent of the potential outcomes to be contrasted. In other words, there is \"no unmeasured confounding\" [@hernan2024WHATIF; @chatton2020].\n\n3. **Positivity:** every individual must have a non-zero chance of receiving the treatment, regardless of their covariate values @westreich2010. We evaluate this assumption in each study by examining changes in religious service attendance from baseline (NZAVS time 10) to the treatment wave (NZAVS time 11). For further discussion of these assumptions in the context of NZAVS studies, see @bulbulia2023a.\n\n\n### Target Population\n\nThe target population for this study comprises New Zealand residents as represented in the baseline wave of the **SIMULATED** New Zealand Attitudes and Values Study (NZAVS) during the years 2018-2019, weighted by New Zealand Census weights for age, gender, and ethnicity (refer to @sibley2021). The NZAVS is a national probability study designed to reflect the broader New Zealand population accurately. Despite its comprehensive scope, the NZAVS does have some limitations in its demographic representation. Notably, it tends to slightly under-sample males and individuals of Asian descent while slightly over-sampling females and Māori (the indigenous peoples of New Zealand). To address these disparities and enhance the accuracy of our findings, we apply constructed survey weights to address the gender imbalance, which was presented largest of threat to external validity. These sample weights were integrated into statistical models using the `weights` option in `lmtp` [@williams2021], following protocols stated in @bulbulia2024PRACTICAL.\n\n\n### Eligibility Criteria\n\nTo be included in the analysis of this study, participants needed to meet the following eligibility criteria:\n\n### Inclusion Criteria\n\n- Enrolled in the **SIMULATED** 2018 wave of the New Zealand Attitudes and Values Study (NZAVS time 10).\n- Missing covariate data at baseline was permitted, and the data was subjected to imputation methods to reduce bias. Only information obtained at baseline was used for such imputation (refer to @zhang2023shouldMultipleImputation).\nParticipants may have been lost to follow-up the end of study NZAVS time 11 or 12. We constructed inverse probability of censoring weights for missing responses at time 11. We adjusted for attrition and non-response at time 12 automatically by specifying a censoring indicator to `lmtp` when estimating outcomes as described below.\n\n### Exclusion Criteria\n\n- Missing data in the perfectionism scale at baseline, wave 10 of the **SIMULATED** New Zealand Attitudes and Values Study.\n\n\nA total of 19,997 **SIMULATED** individuals met these criteria and were included in the study.\n\n\n###  Causal Identification \n\n::: {#tbl-02}\n\n\n\n\n\n\n```{=latex}\n\\examplelongitudinal\n```\n\n\n\n\n\n\nThis table presents a three-wave panel design as described in @vanderweele2020. By adjusting for a rich array of baseline covariates, includeing baseline treatment and baseline outcomes, we reduce the threats to confounding control in a three-wave panel design. @bulbulia2024PRACTICAL.\n:::\n\n\n@tbl-02 presents three Causal Directed Acyclic Graph (DAG) that describe our confounding control  (identification strategy). Our approach consistently applies the same identification strategy across all functions estimated in this study. Unlike standard causal diagrams, SWIGs allow us to *separately* read the factorisation of the conditional dependencies for the distribution of each set of counterfactual outcomes under each modified treatment policy [@richardson2013swigsprimer]. Note, that the natural value of the treatment $A$ is obtained both from its observed instances and from baseline historical data, including the baseline treatment. This method ensures that our analysis accurately captures the causal effects of flexible treatment regimes that rely on levels of religious service attendance at the treatment wave, while ensuring balance for each treatment function that we compare [@diaz2012population; @young2014identification; @diaz2021nonparametric]. \n\n\n### Confounding Control\n\nTo manage confounding in our analysis, we implement @vanderweele2019's *modified disjunctive cause criterion* by following these steps:\n\n  1. **Identified all common causes** of both the treatment and outcomes to ensure a comprehensive approach to confounding control.\n  2. **Excluded instrumental variables** that affect the exposure but not the outcome. Instrumental variables do not contribute to controlling confounding and can reduce the efficiency of the estimates.\n  3. **Included proxies for unmeasured confounders** affecting both exposure and outcome. According to the principles of d-separation, using proxies allows us to control for their associated unmeasured confounders indirectly.\n  4. **Controlled for baseline exposure** and **baseline outcome**. Both are used as proxies for unmeasured common causes, enhancing the robustness of our causal estimates.\n\n[Appendix B](#appendix-demographics) details the covariates we included for confounding control. These methods adhere to the guidelines provided in [@bulbulia2024PRACTICAL] and were pre-specified in our study protocol [https://osf.io/ce4t9/](https://osf.io/ce4t9/).\n\n\n\n### Missing Data\nTo mitigate bias from missing data, we implement the following strategies:\n\n**Baseline missingness**: we employed the `ppm` algorithm from the `mice` package in R [@vanbuuren2018] to impute missing baseline data. This method allowed us to reconstruct incomplete datasets by estimating a plausible value for missing observation. Because we could only pass one data set to the `lmtp`, we employed single imputation. About 2% of covariate values were missing at baseline. Eligibility for the study required fully observed baseline treatment measures as well as treatment wave treatment measures. Again, we only used baseline data to impute baseline missingness (refer to @zhang2023shouldMultipleImputation).\n\n**treatment-wave missingness in time 11 (treatment wave)**: to adjust for censoring in the treatment wave, we estimated inverse probability of censoring weights by predicting loss-to follow up from all indicators, including the baseline values of the treatment and outcomes. We used same superlearners employed in the causal estimation models (`ranger`, `xgboost`, `glmnet`) and impliented 10-fold cross validation.  \n\n**Outcome missingness in time 12 (outcome wave)**: to address confounding and selection bias arising from missing responses and panel attrition, we applied censoring weights obtained using nonparametric machine learning ensembles afforded by the `lmtp` package (and its dependencies) in R [@williams2021]. \n\n### Statistical Estimator\n\n<!-- We use a Sequentially Doubly-Robust (SDR) estimator designed for the analysis of longitudinal data within causal inference frameworks [@díaz2021]. The estimator is grounded in the principles of robust semi-parametric statistics and is characterised first by its sequential approach to handling time-varying treatments and outcomes and, secondly, its double robustness property. -->\n\n<!-- Fundamentally, the SDR estimator operates by iteratively regressing pseudo-outcomes on observed treatments and covariates at each time point, starting from the end of the observation period and proceeding backwards. This iterative process employs the concept of pseudo-outcomes, which are updated at each step based on the outcome of the regression, incorporating information from both the treatment mechanism and the outcome model. -->\n\n<!-- A key feature of the SDR estimator is its 'multiply robust' property, implying that the estimator remains consistent if, for each time point, either the model for the treatment assignment or the model for the outcome, conditional on past treatments and covariates, is correctly specified. This property significantly enhances the estimator's applicability to real-world scenarios such as ours, where model misspecification is a common challenge. Furthermore, the marriage of SDR and machine learning reduces the dependence of inference on restrictive modelling assumptions and introduces an additional layer of robustness. For further details see [@hoffman2022; @hoffman2023; @díaz2021]. Estimation was performed using the `lmtp` package [@williams2021].  -->\n\n\nWe perform statistical estimation using semi-parametric Targeted Learning, specifically a Targeted Minimum Loss-based Estimation (TMLE) estimator. TMLE is a robust method that combines machine learning techniques with traditional statistical models to estimate causal effects while providing valid statistical uncertainty measures for these estimates [@van2014targeted; @van2012targeted].\n\nTMLE operates through a two-step process that involves modelling both the outcome and treatment (exposure). Initially, TMLE employs machine learning algorithms to flexibly model the relationship between treatments, covariates, and outcomes. This flexibility allows TMLE to account for complex, high-dimensional covariate spaces *efficiently* without imposing restrictive model assumptions [@van2014discussion; @vanderlaan2011; @vanderlaan2018]. The outcome of this step is a set of initial estimates for these relationships.\n\nThe second step of TMLE involves \"targeting\" these initial estimates by incorporating information about the observed data distribution to improve the accuracy of the causal effect estimate. TMLE achieves this precision through an iterative updating process, which adjusts the initial estimates towards the true causal effect. This updating process is guided by the efficient influence function, ensuring that the final TMLE estimate is as close as possible, given the measures and data, to the targeted causal effect while still being robust to model-misspecification in either the outcome or the treatment model [@van2014discussion].\n\nAgain, a central feature of TMLE is its double-robustness property. If either the treatment model or the outcome model is correctly specified, the TMLE estimator will consistently estimate the causal effect. Additionally, we used cross-validation to avoid over-fitting, following the pre-stated protocols in @bulbulia2024PRACTICAL.  The integration of TMLE and machine learning technologies reduces the dependence on restrictive modelling assumptions and introduces an additional layer of robustness. For further details of the specific targeted learning strategy we favour, see [@hoffman2022; @hoffman2023; @díaz2021]. We perform estimation using the `lmtp` package [@williams2021]. We used the `superlearner` library for semi-parametric estimation with the predefined libraries `SL.ranger`, `SL.glmnet`, and `SL.xgboost` [@polley2023; @xgboost2023; @Ranger2017]. We created graphs, tables and output reports using the `margot` package [@margot2024]. \n\n\n\n### Sensitivity Analysis Using the E-value\n\nTo assess the sensitivity of results to unmeasured confounding, we report VanderWeele and Ding's \"E-value\" in all analyses [@vanderweele2017]. The E-value quantifies the minimum strength of association (on the risk ratio scale) that an unmeasured confounder would need to have with both the exposure and the outcome (after considering the measured covariates) to explain away the observed exposure-outcome association [@vanderweele2020; @linden2020EVALUE]. To evaluate the strength of evidence, we use the bound of the E-value 95% confidence interval closest to 1.\n\n\n### Scope of Interventions\n\nTo illustrate the magnitude of the shift interventions we contrast, we provide histograms in @fig-hist, that display the distribution of treatments during the treatment wave. @fig-hist: The intervention less than one unit at the top of the range is presented in colour.\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![This figure shows a histogram of responses to religious service frequency in the baseline + 1 wave. Responses above eight were assigned to eight, and values were rounded to the nearest whole number. The red dashed line shows the population average. (A) Responses in the gold bars are shifted to four on the Regular Religious Service intervention. All those responses in grey (four and above) remain unchanged. (B) On the zero-intervention, responses in the blue bars denote those shifted under the zero-intervention treatment.](example-manuscript_files/figure-html/fig-hist-1.png){#fig-hist width=960}\n:::\n:::\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n### Evidence for Change in the Treatment Variable\n\n@tbl-transition clarifies the change in the treatment variable from the baseline wave to the baseline + 1 wave across the sample.  Assessing change in a variable is essential for evaluating the positivity assumption and recovering evidence for the incident exposure effect of the treatment variable [@vanderweele2020; @danaei2012; @hernan2024WHATIF]. We find that state 4 (weekly attendance) and state 0 present the highest overall. However, movement between these states reveals they are not deterministic. States 1, 2, 3, and 5 exhibit more frequent jumps in and out of these states, suggesting lower stability and/or measurement error.  \n\n\n\n\n\n\n\n::: {#tbl-transition .cell tbl-cap='This transition matrix captures shifts in states across across the treatment intervals. Each cell in the matrix represents the count of individuals transitioning from one state to another. The rows correspond to the treatment at baseline (From), and the columns correspond to the state at the following wave (To). **Diagonal entries** (in **bold**) correspond to the number of individuals who remained in their initial state across both waves. **Off-diagonal entries** correspond to the transitions of individuals from their baseline state to a different state in the treatment wave.\nA higher number on the diagonal relative to the off-diagonal entries in the same row indicates greater stability in a state. Conversely, higher off-diagonal numbers suggest more frequent shifts from the baseline state to other states.'}\n::: {.cell-output-display}\n\n\n|  From   | State 1 | State 2  | State 3  | State 4  | State 5 | State 6 | State 7 |\n|:-------:|:-------:|:--------:|:--------:|:--------:|:-------:|:-------:|:-------:|\n| State 1 | **893** |   484    |   194    |    40    |   16    |    3    |    2    |\n| State 2 |   657   | **1737** |   904    |   283    |   78    |    9    |    1    |\n| State 3 |   237   |   1073   | **1368** |   768    |   245   |   40    |    5    |\n| State 4 |   66    |   335    |   803    | **1076** |   523   |   108   |   10    |\n| State 5 |   24    |    77    |   253    |   531    | **579** |   223   |   26    |\n| State 6 |    7    |    9     |    38    |   106    |   205   | **216** |   53    |\n| State 7 |    2    |    1     |    5     |    8     |   25    |   45    | **48**  |\n\n\n:::\n:::\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n\n\n## Results\n\n### Study 1: Causal Effects of Perfectionism on Anxiety and Depression \n\nResults for the treatment contrasts between perfectionism and the status quo on mental health are displayed in @fig-1_1 and @tbl-1_1. These results are measured on the causal difference scale.\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![This figure reports the results of model estimates for the causal effects of a one unit increase in perfectionism vs the status quo depression and anxiety at the end of the study. Contrasts are expressed in standard deviation units.](example-manuscript_files/figure-html/fig-1_1-1.png){#fig-1_1 width=960}\n:::\n:::\n\n::: {#tbl-1_1 .cell tbl-cap='This table reports the results of model estimates for the causal effects of a one unit increase in perfectionism vs the status quo depression and anxiety at the end of the study. Contrasts are expressed in standard deviation units.'}\n::: {.cell-output-display}\n\n\n|                     | E[Y(1)]-E[Y(0)]| 2.5 %| 97.5 %| E_Value| E_Val_bound|\n|:--------------------|---------------:|-----:|------:|-------:|-----------:|\n|marginal: anxiety    |           0.115| 0.096|  0.135|   1.460|       1.405|\n|marginal: depression |           0.141| 0.120|  0.162|   1.531|       1.473|\n\n\n:::\n:::\n\n\n\n\n\n\n\nA Longitudinal Modified Treatment Policy (LMTP) calculates the expected outcome difference between treatment and contrast conditions over a sequential regime of treatments for a prespecified target population.\n\nFor 'marginal: depression', the effect estimate on the causal_difference scale is 0.141 [0.12, 0.162]. The E-value for this estimate is 1.531, with a lower bound of 1.473. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.473 to negate the observed effect. Weaker confounding would not overturn it. Here, **there is evidence for causality**.\n\nFor 'marginal: anxiety', the effect estimate on the causal_difference scale is 0.115 [0.096, 0.135]. The E-value for this estimate is 1.46, with a lower bound of 1.405. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.405 to negate the observed effect. Weaker confounding would not overturn it. Here, **there is evidence for causality**.\n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n\n\n#### Subgroup Analysis: Those Born in NZ \n\n@fig-2_1 present results for the treatment contrasts within the two subgroups, evaluating the effect of a one unit increase in perfectionism vs the status qu. These results are presented on the difference scale in standardized units.\n\n@tbl-2_1 presents the results for those born in New Zealand. @tbl-2_2 presents results for those born overseas.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {#tbl-2_1 .cell tbl-cap='This table reports the results of model estimates for in the population of residents born in New Zealand. We again estimate the causal effects of a one unit increase in perfectionism vs the status quo depression and anxiety at the end of the study. Contrasts are expressed in standard deviation units..'}\n::: {.cell-output-display}\n\n\n|                    | E[Y(1)]-E[Y(0)]| 2.5 %| 97.5 %| E_Value| E_Val_bound|\n|:-------------------|---------------:|-----:|------:|-------:|-----------:|\n|born NZ: anxiety    |           0.113| 0.093|  0.134|   1.455|       1.394|\n|born NZ: depression |           0.145| 0.121|  0.168|   1.542|       1.478|\n\n\n:::\n:::\n\n\n\n\n\n\n\nFor 'born NZ: depression', the effect estimate is 0.145 [0.121, 0.168]. The E-value for this estimate is 1.542, with a lower bound of 1.478. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.478 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\nFor 'born NZ: anxiety', the effect estimate is 0.113 [0.093, 0.134]. The E-value for this estimate is 1.455, with a lower bound of 1.394. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.394 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\n\n\n\n\n\n\n::: {#tbl-2_2 .cell tbl-cap='This table reports the results of model estimates for in the population of residents not born in New Zealand (born overseas). We again estimate the causal effects of a one unit increase in perfectionism vs the status quo depression and anxiety at the end of the study. Contrasts are expressed in standard deviation units.'}\n::: {.cell-output-display}\n\n\n|                          | E[Y(1)]-E[Y(0)]| 2.5 %| 97.5 %| E_Value| E_Val_bound|\n|:-------------------------|---------------:|-----:|------:|-------:|-----------:|\n|born overseas: anxiety    |           0.113| 0.075|  0.152|   1.455|       1.342|\n|born overseas: depression |           0.143| 0.101|  0.185|   1.537|       1.424|\n\n\n:::\n:::\n\n\n\n\n\n\nFor 'born overseas: depression', the effect estimate is 0.143 [0.101, 0.185]. The E-value for this estimate is 1.537, with a lower bound of 1.424. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.424 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\nFor 'born overseas: anxiety', the effect estimate is 0.113 [0.075, 0.152]. The E-value for this estimate is 1.455, with a lower bound of 1.342. At this lower bound, unmeasured confounders would need a minimum association strength with both the intervention sequence and outcome of 1.342 to negate the observed effect. Weaker confounding would not overturn it. We infer **evidence for causality**.\n\n\n## Findings\n\nComparing the difference in the mean outcomes between to the two groups for anxiety:  The difference in means is 2e-04 with a standard error of 0.0223 and a 95% CI of [-0.0436, 0.0439].. We therefore do not detect a reliable difference between those born in New Zealand and those born elsewhere. \n\nComparing the difference in the mean outcomes between to the two groups for depression: The difference in means is 2e-04 with a standard error of 0.0223 and a 95% CI of [-0.0436, 0.0439].. We therefore do not detect a reliable difference between those born in New Zealand and those born elsewhere. \n\n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n### Additional Study: Comparison of Causal Inference Results with Cross-Sectional Regressions\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nTo better evaluate the contributions of our methodology to current practice, we conducted a series of cross-sectional analyses using the baseline wave data. We quantified the statistical associations between religious service attendance and our focal prosocial outcomes. We included all regression covariates from the causal models (including sample weights) for each analysis, obviously omitting the outcome measured at baseline, i.e. the response variable.\n\n**Cross-sectional anxiety result**: the change in expected kessler-6 anxiety for a one-unit increase in perfectionism is b = 0.31; (95% CI 0.30, 0.32). This result is 2.65 per cent greater than the effect estimated from the '+1 vs. status quo' causal contrast (0.115), indicating an **overstatement in the cross-sectional regression model.**\n\n**Cross-sectional depression result**: the change in expected kessler-6 depression for a one-unit increase in perfectionism is b = 0.34; (95% CI 0.33, 0.35). This result is 2.43 per cent greater than the effect estimated from the '+1 vs. status quo' causal contrast (0.141), indicating an **overstatement in the cross-sectional regression model.**\n\n\nThese findings underscore that the results of cross-sectional regressions, although suggestive, can considerably diverge from those obtained from the causal analysis of panel data.\n\n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n\n\n## Discussion \n\n### Considerations\n\nFirst, as stated above, our causal inferences turn on three assumptions, which are worth revisiting: \n\n(i). **Unmeasured confounding**: although we employ robust methods for causal inference, our results depend on the effectiveness of our strategy to control for confounding. Our sensitivity analyses address the potential impacts of unmeasured confounders. Nevertheless, the presence and influence of such confounders are uncertain and unverifiable from our data.\n\n(ii). **Causal consistency**: the observed outcomes must correspond to the counterfactual treatments contrasted. Although \"religious service attendance\" may appear conditionally independent of the outcomes given baseline covariates, interpreting these interventions remains challenging. \"Religious service attendance\" varies widely, encompassing everything from informal gatherings at homes to formal services in cathedrals across New Zealand's religious diversity. This type of \"treatment\" does not mirror a straightforward medical intervention like a vaccine. The heterogeneity of \"religious service\" limits the clarity of our results, an issue no amount of data or analysis can resolve because \"religious service\" reflects a broad spectrum of community activities.\n\n(iii). **Positivity**: we have confirmed that religious service attendance varies within our sample and have used semi-parametric models with ensemble learning and cross-validation to prevent data over-extrapolation and model over-fitting. Conceptually, it is crucial for valid causal inference that every potential level of \"treatment\" to religious services is realistically possible (refer to discussion in @vanderweele2017causaleffectsService). Although there are instances realised in our data of secular individuals initiating religious service and frequent attendees stopping (refer to @tbl-transition), it might stretch credulity too far to imagine that such changes are possible for everyone.\n\n\nSecond, our study confronts the spectre of **measurement error**: both direct and correlated measurement errors can introduce biases, either by implying effects where none exist or by attenuating true effects [@vanderweele2012MEASUREMENT]. Importantly, evaluating prosociality using multiple measures while also controlling for these measures and the treatment at baseline helps to mitigate measurement error concerns. Nevertheless, unknown combinations of measurement error might nevertheless bias our results. The outcomes and estimates we report here are best-considered approximations.\n\nThird, we do not examine **treatment effect heterogeneity**: identifying which subgroups experience the strongest responses remains a task for future research. Such investigations are crucial for making informed policy decisions and tailoring advice relevant to those subgroups of the population who might benefit most. Perhaps the most obvious stratum is religious affiliates [@vanderweele2017causaleffectsService].\n\nFourth, the **transportability of our findings remains unclear**: New Zealand is our target population. Our findings generalise to this population. However, the transportability of our findings to other settings—whether our results generalise beyond our targeted New Zealand population—remains an open question, a matter for future investigations. \n\n\n### Observations and Recommendations\n\n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n\n### Ethics\n\n {**authors blinded**} \n\n### Data Availability\n\n{**authors blinded**} \n\n\n### Acknowledgements\n\n {**authors blinded**} \n\n\n### Author Statement\n\n {**authors blinded**} \n\n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n\n## Appendix A: Measures {#appendix-measures}\n\n#### Age (waves: 1-15)\n\nWe asked participants' ages in an open-ended question (\"What is your age?\" or \"What is your date of birth?\").\n\n\n#### Born in New Zealand\n\n\n#### Charitable Donations  (Study 1 outcome)\n\nUsing one item from @hoverd_religious_2010, we asked participants, \"How much money have you donated to charity in the last year?\". \n\n<!-- To stabilise this indicator, we took the natural log of the response + 1. -->\n\n\n#### Charitable Volunteering  (Study 1 outcome)\n\n\nWe measured hours of volunteering using one item from @sibley2011: \"Hours spent … voluntary/charitable work.\"\n\n<!-- To stabilise this indicator, we took the natural log of the response + 1. -->\n\n#### Children Number (waves: 1-3, 4-15)\n\nWe measured the number of children using one item from @Bulbulia_2015. We asked participants, \"How many children have you given birth to, fathered, or adopted. How many children have you given birth to, fathered, or adopted?\" or \"How many children have you given birth to, fathered, or adopted. How many children have you given birth to, fathered, and/or parented?\" (waves: 12-15).\n\n<!-- Here, we used responses to create a binary indicator for parenthood: Parent Yes = 1/ No = 0.  -->\n\n\n\n<!-- #### Community: Sense of Community (Study 2 outcome) -->\n\n<!-- We measured a sense of community with a single item from @sengupta2013: \"I feel a sense of community with others in my local neighbourhood.\" Participants answered on a scale of 1 (strongly disagree) to 7 (strongly agree). -->\n\n\n<!-- #### Community: Felt Belongingness  (Study 2 outcome) -->\n\n<!-- We assessed felt belongingness with three items adapted from the Sense of Belonging Instrument [@hagerty1995]: (1) \"Know that people in my life accept and value me\"; (2) \"Feel like an outsider\"; (3) \"Know that people around me share my attitudes and beliefs\". Participants responded on a scale from 1 (Very Inaccurate) to 7 (Very Accurate). The second item was reversely coded. -->\n\n<!-- #### Community: Social Support (Study 2 outcome) -->\n\n<!-- Participants perceived social support was measured using three items from @cutrona1987 and @williams_cyberostracism_2000: (1) \"There are people I can depend on to help me if I really need it\"; (2) \"There is no one I can turn to for guidance in times of stress\"; (3) \"I know there are people I can turn to when I need help.\" Participants indicated how much they agreed with those items (1 = Strongly Disagree to 7 = Strongly Agree). The second item was negatively worded, so we reversely recorded the responses to this item. -->\n\n#### Disability\n\nWe assessed disability with a one-item indicator adapted from @verbrugge1997. It asks, \"Do you have a health condition or disability that limits you and that has lasted for 6+ months?\" (1 = Yes, 0 = No).\n\n\n#### Education Attainment (waves: 1, 4-15)\n\nWe asked participants, \"What is your highest level of qualification?\". We coded participants' highest finished degree according to the New Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with overseas school quals coded as Level 3, and all other ancillary categories coded as missing) See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf\n\n#### Employment (waves: 1-3, 4-11)\n\nWe asked participants, \"Are you currently employed? (This includes self-employed or casual work)\".\n\n<!-- #### European (waves: 1-15) -->\n\n<!-- Participants were asked, \"Which ethnic group do you belong to (NZ census question)?\" or \"Which ethnic group(s) do you belong to? (Open-ended)\" (wave: 3). Europeans were coded as 1, whereas other ethnicities were coded as 0. -->\n\n#### Ethnicity\n\nBased on the New Zealand Census, we asked participants, \"Which ethnic group(s) do you belong to?\". The responses were: (1) New Zealand European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6) Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE, TOKELAUAN. Please state:. We coded their answers into four groups: Maori, Pacific, Asian, and Euro (except for Time 3, which used an open-ended measure).\n\n\n#### Fatigue\n\nWe assessed subjective fatigue by asking participants, \"During the last 30 days, how often did ... you feel exhausted?\" Responses were collected on an ordinal scale (0 = None of The Time, 1 = A little of The Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time).\n\n\n#### Honesty-Humility-Modesty Facet (waves: 10-14)\n\nParticipants indicated the extent to which they agree with the following four statements from @campbell2004 , and @sibley2011 (1 = Strongly Disagree to 7 = Strongly Agree)\n\n```\ni.  I want people to know that I am an important person of high status, (Waves: 1, 10-14)\nii. I am an ordinary person who is no better than others.\niii. I wouldn't want people to treat me as though I were superior to them.\niv. I think that I am entitled to more respect than the average person is.\n```\n\n<!-- #### Has Siblings -->\n\n<!-- \"Do you have siblings?\" [@stronge2019onlychild] -->\n\n#### Hours of Childcare\n\nWe measured hours of exercising using one item from @sibley2011: 'Hours spent … looking after children.\"\n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n\n#### Hours of Housework\n\nWe measured hours of exercising using one item from @sibley2011: \"Hours spent … housework/cooking\"\n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n#### Hours of Exercise\n\nWe measured hours of exercising using one item from @sibley2011: \"Hours spent … exercising/physical activity\" \n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n<!-- #### Hours Volunteering -->\n\n<!-- We measured hours of volunteering using one item from @sibley2011: \"Hours spent … voluntary/charitable work.\" -->\n\n<!-- To stabilise this indicator, we took the natural log of the response + 1. -->\n\n#### Hours of Childcare\n\nWe measured hours of exercising using one item from @sibley2011: 'Hours spent … looking after children.\"\n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n\n#### Hours of Exercise\n\nWe measured hours of exercising using one item from @sibley2011: \"Hours spent … exercising/physical activity\" \n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n\n#### Hours of Housework\n\nWe measured hours of exercising using one item from @sibley2011: \"Hours spent … housework/cooking\"\n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n\n#### Hours of Sleep\n\nParticipants were asked, \"During the past month, on average, how many hours of *actual sleep* did you get per night?\".\n\n\n#### Hours of Work\n\nWe measured work hours using one item from @sibley2011: \"Hours spent … working in paid employment.\"\n\nTo stabilise this indicator, we took the natural log of the response + 1.\n\n\n#### Income (waves: 1-3, 4-15)\n\nParticipants were asked, \"Please estimate your total household income (before tax) for the year XXXX\". To stabilise this indicator, we first took the natural log of the response + 1, and then centred and standardised the log-transformed indicator.\n\n<!-- #### Job Security (waves: 1-3,4-7,9-15) -->\n\n<!-- Participants indicated their feeling of job security by answering \"How secure do you feel in your current job?\" on a scale from 1 (not secure) to 7 (very secure). -->\n\n\n#### Kessler-6: Psychological Distress  (waves: 2-3,4-15)\n\nWe measured psychological distress using the Kessler-6 scale (kessler2002?), which exhibits\nstrong diagnostic concordance for moderate and severe psychological distress in large, crosscultural\nsamples (kessler2010?; prochaska2012?). Participants rated during the past 30\ndays, how often did… (1) “… you feel hopeless”; (2) “… you feel so depressed that nothing\ncould cheer you up”; (3) “… you feel restless or fidgety”; (4)“… you feel that everything was\nan effort”; (5) “… you feel worthless”; (6) ” you feel nervous?” Ordinal response alternatives\nfor the Kessler-6 are: “None of the time”; “A little of the time”; “Some of the time”; “Most of\nthe time”; “All of the time.”\n\n\n#### Male Gender (waves: 1-15)\n\nWe asked participants' gender in an open-ended question: \"what is your gender?\" or \"Are you male or female?\" (waves: 1-5). Female was coded as 0, Male as 1, and gender diverse coded as 3 [@fraser_coding_2020]. (or 0.5 = neither female nor male)\n\nHere, we coded all those who responded as Male as 1, and those who did not as 0.\n\n\n#### Mini-IPIP 6 (waves: 1-3,4-15)\n\nWe measured participants' personalities with the Mini International Personality Item Pool 6 (Mini-IPIP6) [@sibley2011], which consists of six dimensions and each dimension is measured with four items:\n\n1.  agreeableness,\n\n    i.  I sympathize with others' feelings.\n    ii. I am not interested in other people's problems. (r)\n    iii. I feel others' emotions.\n    iv. I am not really interested in others. (r)\n\n2.  conscientiousness,\n\n    i.  I get chores done right away.\n    ii. I like order.\n    iii. I make a mess of things. (r)\n    iv. I often forget to put things back in their proper place. (r)\n\n3.  extraversion,\n\n    i.  I am the life of the party.\n    ii. I don't talk a lot. (r)\n    iii. I keep in the background. (r)\n    iv. I talk to a lot of different people at parties.\n\n4.  honesty-humility,\n\n    i.  I feel entitled to more of everything. (r)\n    ii. I deserve more things in life. (r)\n    iii. I would like to be seen driving around in a very expensive car. (r)\n    iv. I would get a lot of pleasure from owning expensive luxury goods. (r)\n\n5.  neuroticism, and\n\n    i.  I have frequent mood swings.\n    ii. I am relaxed most of the time. (r)\n    iii. I get upset easily.\n    iv. I seldom feel blue. (r)\n\n6.  openness to experience\n\n    i.  I have a vivid imagination.\n    ii. I have difficulty understanding abstract ideas. (r)\n    iii. I do not have a good imagination. (r)\n    iv. I am not interested in abstract ideas. (r)\n\nEach dimension was assessed with four items and participants rated the accuracy of each item as it applies to them from 1 (Very Inaccurate) to 7 (Very Accurate). Items marked with (r) are reverse coded.\n\n\n#### NZ-Born (waves: 1-2,4-15)\n\nWe asked participants, \"Which country were you born in?\" or \"Where were you born? (please be specific, e.g., which town/city?)\" (waves: 6-15).\n\n\n#### NZ Deprivation Index (waves: 1-15)\n\nWe used the NZ Deprivation Index to assign each participant a score based on where they live [@atkinson2019]. This score combines data such as income, home ownership, employment, qualifications, family structure, housing, and access to transport and communication for an area into one deprivation score.\n\n\n#### NZSEI Occupational Prestige and Status (waves: 8-15)\n\nWe assessed occupational prestige and status using the New Zealand Socio-economic Index 13 (NZSEI-13) [@fahy2017a]. This index uses the income, age, and education of a reference group, in this case the 2013 New Zealand census, to calculate a score for each occupational group. Scores range from 10 (Lowest) to 90 (Highest). This list of index scores for occupational groups was used to assign each participant an NZSEI-13 score based on their occupation.\n\nWe assessed occupational prestige and status using the New Zealand Socio-economic Index 13 (NZSEI-13) [@fahy2017]. This index uses the income, age, and education of a reference group, in this case, the 2013 New Zealand census, to calculate a score for each occupational group. Scores range from 10 (Lowest) to 90 (Highest). This list of index scores for occupational groups was used to assign each participant an NZSEI-13 score based on their occupation.\n\n<!-- We asked participants, \"If you are a parent, what is the birth date of your eldest child?\". -->\n<!-- #### Parent (waves: 5-15) -->\n\n<!-- We asked participants, \"If you are a parent, what is the birth date of your eldest child?\" or \"If you are a parent, in which year was your eldest child born?\" (waves: 10-15). Parents were coded as 1, while the others were coded as 0. --> \n\n\n\n#### Opt-in\n\nThe New Zealand Attitudes and Values Study allows opt-ins to the study. Because the opt-in population may differ from those sampled randomly from the New Zealand electoral roll; although the opt-in rate is low, we include an indicator (yes/no) for this variable.\n\n\n\n#### Partner (No/Yes)\n\n\"What is your relationship status?\" (e.g., single, married, de-facto, civil union, widowed, living together, etc.)\n\n\n#### Politically Conservative \n\nWe measured participants' political conservative orientation using a single item adapted from @jost_end_2006-1.\n\n\"Please rate how politically liberal versus conservative you see yourself as being.\"\n\n(1 = Extremely Liberal to 7 = Extremely Conservative)\n\n\n##### Religious Service Attendance\n\nIf participants answered *yes* to \"Do you identify with a religion and/or spiritual group?\" we measured their frequency of church attendence using one item from @sibley2012: \"how many times did you attend a church or place of worship in the last month?\". Those participants who were not religious were imputed a score of \"0\".\n\n#### Rural/Urban Codes\n\nParticipants residence locations were coded according to a five-level ordinal categorisation ranging from \"Urban\" to Rural, see @sibley2021.\n\n<!-- #### Politically Right Wing  -->\n\n<!-- We measured participants' political right-wing orientation using a single item adapted from @jost_end_2006-1. -->\n\n<!-- \"Please rate how politically left-wing versus right-wing you see yourself as being.\" -->\n\n<!-- (1 = Extremely left-wing to 7 = Extremely right-wing) -->\n\n\n<!-- #### Religion Affiliation -->\n\n<!-- Participants were asked to indicate their religion identification (\"Do you identify with a religion and/or spiritual group?\") on a binary response (1 = Yes, 0 = No). We then asked, \"What religion or spiritual group?\" These questions are used in the New Zealand Census -->\n\n\n<!-- #### Support -->\n\n<!-- Participants' perceived social support was measured using three items from @cutrona1987 and @williams_cyberostracism_2000: (1) \"There are people I can depend on to help me if I really need it\"; (2) \"There is no one I can turn to for guidance in times of stress\"; (3) \"I know there are people I can turn to when I need help.\" Participants indicated how much they agreed with those items (1 = Strongly Disagree to 7 = Strongly Agree). The second item was negatively worded, so we reversely recorded the responses to this item. -->\n\n#### Short-Form Health\n\nParticipants' subjective health was measured using one item (\"Do you have a health condition or disability that limits you, and that has lasted for 6+ months?\"; 1 = Yes, 0 = No) adapted from @verbrugge1997.\n\n\n#### Sample Origin\n\nWave enrolled in NZAVS, see @sibley2021.\n\n<!-- #### Socialising (time 10, time 11) -->\n\n<!-- As part of the time usage measures, participants were asked to state how many hour the spent in activities related to socialising with the following groups: -->\n\n<!--   - Hours spent … socialising with family -->\n<!--   - Hours spent … socialising with friends -->\n<!--   - Hours spent … socialising with community groups -->\n\n<!--   <!-- - Hours spent … socialising with religious groups -->\n\n\n#### Support received: money (waves 10-12) (Study 4 outcomes)\n\nThe NZAVS has a 'revealed' measure of received help and support measured in hours of support in the previous week. The items are: \n\n\n*Please estimate how much help you have received from the following sources in the last week?*\n\n- *family...MONEY (hours)*\n- *friends...MONEY (hours)*\n- *members of my community...MONEY (hours)*\n\n\nBecause this measure is highly variable, we convert responses to binary indicators: *0 = none/1 any*\n\n\n#### Support received: time (waves 10-13) (Study 3 outcomes)\n\n*Please estimate how much help you have received from the following sources in the last week.*\n\n- *family...TIME (hours)*\n- *friends...TIME (hours)*\n- *members of my community...TIME (hours)*\n\nBecause this measure is highly variable, we convert responses to binary indicators: *0 = none/1 any*\n  \n\n#### Total Siblings\n\nParticipants were asked the following questions related to sibling counts: \n \n - Were you the 1st born, 2nd born, or 3rd born, etc, child of your mother?\n - Do you have siblings?\n - How many older sisters do you have?\n - How many younger sisters do you have?\n - How many older brothers do you have?\n - How many younger brothers do you have?\n\nA single score was obtained from sibling counts by summing responses to the \"How many...\" items. From these scores, an ordered factor was created ranging from 0 to 7, where participants with more than 7 siblings were grouped into the highest category. \n\n\n<!-- #### Volunteers -->\n\n<!-- We asked participants,\"Please estimate how many hours you spent doing each of the following things last week\" and responded to an item (\"voluntary/charitable work\") from [@sibley2011]. -->\n\n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n\n## Appendix B. Baseline Demographic Statistics {#appendix-demographics}\n\n\n\n\n\n\n\n\n::: {#tbl-table-demography .cell tbl-cap='Baseline demographic statistics'}\n::: {.cell-output-display}\n\n\n|**Exposure + Demographic Variables** |**N = 19,997** |\n|:------------------------------------|:--------------|\n|__Age__                              |NA             |\n|Mean (SD)                            |49 (14)        |\n|Range                                |18, 98         |\n|IQR                                  |39, 60         |\n|__Male__                             |7,425 (37%)    |\n|__Edu__                              |NA             |\n|Mean (SD)                            |5.29 (2.72)    |\n|Range                                |0.00, 10.00    |\n|IQR                                  |3.00, 7.00     |\n|Unknown                              |510            |\n|__Eth Cat__                          |NA             |\n|euro                                 |15,850 (80%)   |\n|maori                                |2,280 (12%)    |\n|pacific                              |498 (2.5%)     |\n|asian                                |1,107 (5.6%)   |\n|Unknown                              |262            |\n|__Partner__                          |14,501 (75%)   |\n|Unknown                              |649            |\n|__Employed__                         |15,884 (80%)   |\n|Unknown                              |39             |\n|__Born Nz__                          |15,436 (78%)   |\n|Unknown                              |232            |\n|__Neighbourhood Community__          |NA             |\n|Mean (SD)                            |4.20 (1.67)    |\n|Range                                |1.00, 7.00     |\n|IQR                                  |2.99, 5.95     |\n|Unknown                              |113            |\n|__Household Inc log__                |NA             |\n|Mean (SD)                            |11.39 (0.76)   |\n|Range                                |0.69, 14.40    |\n|IQR                                  |11.00, 11.92   |\n|Unknown                              |1,529          |\n|__Parent__                           |14,037 (71%)   |\n|Unknown                              |156            |\n|__Religion Religious__               |7,148 (36%)    |\n|Unknown                              |301            |\n|__Urban__                            |12,291 (62%)   |\n|Unknown                              |129            |\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n@tbl-table-demography baseline demographic statistics for couples who met inclusion criteria.\n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n\n\n##  Appendix C: Treatment Statistics {#appendix-exposures}\n\n\n\n\n\n\n\n\n::: {#tbl-table-exposures-code .cell tbl-cap='Exposures at baseline and baseline + 1 (treatment) wave'}\n::: {.cell-output-display}\n\n\n|**Exposure Variables by Wave** |**2018**, N = 19,997 |**2019**, N = 19,997 |\n|:------------------------------|:--------------------|:--------------------|\n|__Perfectionism__              |3.02 (2.03, 4.04)    |2.99 (2.00, 4.02)    |\n|Unknown                        |0                    |5,558                |\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\ntbl-table-exposures-code presents baseline (NZAVS time 10) and exposure wave (NZAVS time 11) statistics for the exposure variable: perfectionism (range 1-7). \n\n<!-- Responses coded as eight or above were coded as \"8\". This decision to avoid spare treatments was based on theoretical grounds, namely, that daily exposure would be similar in its effects to more than daily exposure. We note that causal contrasts were obtained for projects with either no attendance or four or more visits per month. Hence this simplification of the measure is unlikely to affect theoretical and practical inferences. All models adjusted for the pandemic alert level because the treatment wave (NZAVS time 11) occurred during New Zealand's COVID-19 pandemic. The pandemic is not a \"confounder\" because a confounder must be related to the treatment and the outcome. At the end of the study, all participants had been exposed to the pandemic.  However, to satisfy the causal consistency assumption, all treatments must be conditionally equivalent within levels of all covariates [@vanderweele2013]. Because COVID affected the ability or willingness of individuals to attend religious service, we included the lockdown condition as a covariate [@sibley2021]. To better enable conditional independence within levels of the treatment variable, we conditioned on the lead value of COVID-alert level at baseline. To mitigate systematic biases arising from attrition and missingness, the `lmtp` package uses inverse probability of censoring weights, which were used when estimating the causal effects of the exposure on the outcome.  -->\n\n\n\n<!-- ### Binary Transition Table for The Treatment -->\n\n<!-- ```{r} -->\n<!-- #| label: tbl-transition-tablegain -->\n<!-- #| tbl-cap: \"Transition table for stability and change in regular religious service (4x per month) between baseline and treatment wave.\" -->\n<!-- #| eval: true -->\n<!-- #| include: true -->\n<!-- #| echo: false -->\n\n<!-- transition_table_binary_gain <-margot::here_read(\"transition_table_binary_gain\") -->\n\n<!-- transition_table_binary_gain$table -->\n<!-- ``` -->\n\n<!-- @tbl-transition-tablegain presents a transition matrix to evaluate treatment shifts between baseline and treatment wave. Here, we focus on the shift from/to monthly attendance at four or more visits per month. Entries along the diagonal (in bold) indicate the number of individuals who **stayed** in their initial state. By contrast, the off-diagonal shows the transitions from the initial state (bold) to another state in the following wave (off diagonal). Thus the cell located at the intersection of row $i$ and column $j$, where $i \\neq j$, gives us the counts of individuals moving from state $i$ to state $j$. -->\n\n\n\n\n\n<!-- ```{r} -->\n<!-- #| label: tbl-transition-tableloss -->\n<!-- #| tbl-cap:  \"Transition table for stability and change in zero religious service (0 x per month) between baseline and treatment wave.\" -->\n<!-- #| eval: true -->\n<!-- #| include: true -->\n<!-- #| echo: false -->\n\n<!-- transition_table_binary_zero <-margot::here_read(\"transition_table_binary_zero\") -->\n<!-- transition_table_binary_zero$table -->\n<!-- ``` -->\n\n<!-- @tbl-transition-tableloss presents a transition matrix to evaluate treatment shifts between baseline and treatment wave. Here, we focus on the shift from/to zero religious service attendance. Again, entries along the diagonal (in bold) indicate the number of individuals who **stayed** in their initial state. By contrast, the off-diagonal shows the transitions from the initial state (bold) to another state in the following wave (off diagonal). Thus the cell located at the intersection of row $i$ and column $j$, where $i \\neq j$, gives us the counts of individuals moving from state $i$ to state $j$. -->\n\n\n### Imbalance of Confounding Covariates Treatments \n\n@fig-match_1 shows imbalance of covariates on the treatment at the treatment wave. The variable on which there is strongest imbalance is the baseline measure of religious service attendance. It is important to adjust for this measure both for confounding control and to better estimate an incident exposure effect for the religious service at the treatment wave (in contrast to merely estimating a prevalence effect). See @vanderweele2020.\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![This figure shows the imbalance in covariates on the treatment](example-manuscript_files/figure-html/fig-match_1-1.png){#fig-match_1 width=960}\n:::\n:::\n\n\n\n\n\n\n\n\n##  Appendix D: Baseline and End of Study Outcome Statistics {#appendix-outcomes}\n\n\n\n\n\n\n\n\n::: {#tbl-table-outcomes .cell tbl-cap='Outcomes at baseline and end-of-study'}\n::: {.cell-output-display}\n\n\n|**Outcome Variables by Wave** |**2018**, N = 19,997 |**2020**, N = 19,997 |\n|:-----------------------------|:--------------------|:--------------------|\n|__Kessler Latent Anxiety__    |1.04 (0.66, 1.68)    |1.03 (0.65, 1.67)    |\n|Unknown                       |203                  |6,768                |\n|__Kessler Latent Depression__ |0.33 (0.01, 0.98)    |0.32 (0.01, 0.97)    |\n|Unknown                       |207                  |6,765                |\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n@tbl-table-outcomes presents baseline and end-of-study descriptive statistics for the outcome variables.  \n\n\n\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n## References {.appendix}\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "example-manuscript_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}